// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/auth/v1/credential.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Credential is one credential-bearing header as the caller sent it.
type Credential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header is the canonical (lowercase) metadata key the values arrived under,
	// so a provider can tell an opaque API key from a bearer token without
	// guessing from the format.
	Header string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// values are that header's values in the order the caller sent them. gRPC
	// metadata allows a key to repeat, so this preserves every value rather than
	// silently choosing one.
	Values        []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_api_auth_v1_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_credential_proto_rawDescGZIP(), []int{0}
}

func (x *Credential) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Credential) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_api_auth_v1_credential_proto protoreflect.FileDescriptor

const file_api_auth_v1_credential_proto_rawDesc = "" +
	"\n" +
	"\x1capi/auth/v1/credential.proto\x12\vapi.auth.v1\"<\n" +
	"\n" +
	"Credential\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06valuesB\xab\x01\n" +
	"\x0fcom.api.auth.v1B\x0fCredentialProtoP\x01Z9github.com/temporalio/temporal-proxy/pkg/api/auth/v1;auth\xa2\x02\x03AAX\xaa\x02\vApi.Auth.V1\xca\x02\vApi\\Auth\\V1\xe2\x02\x17Api\\Auth\\V1\\GPBMetadata\xea\x02\rApi::Auth::V1b\x06proto3"

var (
	file_api_auth_v1_credential_proto_rawDescOnce sync.Once
	file_api_auth_v1_credential_proto_rawDescData []byte
)

func file_api_auth_v1_credential_proto_rawDescGZIP() []byte {
	file_api_auth_v1_credential_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_credential_proto_rawDesc), len(file_api_auth_v1_credential_proto_rawDesc)))
	})
	return file_api_auth_v1_credential_proto_rawDescData
}

var file_api_auth_v1_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_auth_v1_credential_proto_goTypes = []any{
	(*Credential)(nil), // 0: api.auth.v1.Credential
}
var file_api_auth_v1_credential_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_credential_proto_init() }
func file_api_auth_v1_credential_proto_init() {
	if File_api_auth_v1_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_credential_proto_rawDesc), len(file_api_auth_v1_credential_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_credential_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_credential_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_credential_proto_msgTypes,
	}.Build()
	File_api_auth_v1_credential_proto = out.File
	file_api_auth_v1_credential_proto_goTypes = nil
	file_api_auth_v1_credential_proto_depIdxs = nil
}
