// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/auth/v1/service.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Auth_FullMethodName = "/api.auth.v1.AuthService/Auth"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService is the contract for a pluggable inbound authenticator. The proxy
// ships with built-in authenticators for a fixed static token and for OIDC/JWKS
// validation. An operator whose identity system fits neither (a policy engine,
// an internal session service, an opaque token only their backend can redeem)
// can instead run their own authenticator as a gRPC server implementing this
// service and point the proxy at it.
//
// The proxy terminates inbound authentication rather than passing it through, so
// this service is asked once per inbound stream, before the stream is routed,
// and nothing reaches an upstream until it admits the caller. The operator
// declares which headers carry the caller's credentials: the proxy lifts those
// into AuthRequest and strips them from the stream it forwards, so a credential
// this service consumes never reaches an upstream.
type AuthServiceClient interface {
	// Auth reports whether the caller behind the current stream may proceed. The
	// verdict travels in the response's decision, and only DECISION_ALLOW admits,
	// so a response left unfilled denies rather than admitting by accident.
	//
	// Return an error only for having reached no verdict at all, such as a backend
	// this server cannot itself reach. The proxy denies either way, but an error
	// keeps its status code, so UNAVAILABLE or DEADLINE_EXCEEDED tells a worker to
	// retry where a denial tells it not to bother. A provider that cannot reach its
	// own backend should report that rather than admit the caller: an authenticator
	// that fails open is worse than one that is down.
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Auth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService is the contract for a pluggable inbound authenticator. The proxy
// ships with built-in authenticators for a fixed static token and for OIDC/JWKS
// validation. An operator whose identity system fits neither (a policy engine,
// an internal session service, an opaque token only their backend can redeem)
// can instead run their own authenticator as a gRPC server implementing this
// service and point the proxy at it.
//
// The proxy terminates inbound authentication rather than passing it through, so
// this service is asked once per inbound stream, before the stream is routed,
// and nothing reaches an upstream until it admits the caller. The operator
// declares which headers carry the caller's credentials: the proxy lifts those
// into AuthRequest and strips them from the stream it forwards, so a credential
// this service consumes never reaches an upstream.
type AuthServiceServer interface {
	// Auth reports whether the caller behind the current stream may proceed. The
	// verdict travels in the response's decision, and only DECISION_ALLOW admits,
	// so a response left unfilled denies rather than admitting by accident.
	//
	// Return an error only for having reached no verdict at all, such as a backend
	// this server cannot itself reach. The proxy denies either way, but an error
	// keeps its status code, so UNAVAILABLE or DEADLINE_EXCEEDED tells a worker to
	// retry where a denial tells it not to bother. A provider that cannot reach its
	// own backend should report that rather than admit the caller: an authenticator
	// that fails open is worse than one that is down.
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Auth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/v1/service.proto",
}
