// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/auth/v1/service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/auth/v1/service.proto\x12\vapi.auth.v1\x1a\x16api/auth/v1/auth.proto2L\n" +
	"\vAuthService\x12=\n" +
	"\x04Auth\x12\x18.api.auth.v1.AuthRequest\x1a\x19.api.auth.v1.AuthResponse\"\x00B\xa8\x01\n" +
	"\x0fcom.api.auth.v1B\fServiceProtoP\x01Z9github.com/temporalio/temporal-proxy/pkg/api/auth/v1;auth\xa2\x02\x03AAX\xaa\x02\vApi.Auth.V1\xca\x02\vApi\\Auth\\V1\xe2\x02\x17Api\\Auth\\V1\\GPBMetadata\xea\x02\rApi::Auth::V1b\x06proto3"

var file_api_auth_v1_service_proto_goTypes = []any{
	(*AuthRequest)(nil),  // 0: api.auth.v1.AuthRequest
	(*AuthResponse)(nil), // 1: api.auth.v1.AuthResponse
}
var file_api_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: api.auth.v1.AuthService.Auth:input_type -> api.auth.v1.AuthRequest
	1, // 1: api.auth.v1.AuthService.Auth:output_type -> api.auth.v1.AuthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_service_proto_init() }
func file_api_auth_v1_service_proto_init() {
	if File_api_auth_v1_service_proto != nil {
		return
	}
	file_api_auth_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_service_proto_rawDesc), len(file_api_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_service_proto = out.File
	file_api_auth_v1_service_proto_goTypes = nil
	file_api_auth_v1_service_proto_depIdxs = nil
}
