// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/auth/v1/target.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Target is what a call is addressing, as the proxy resolved it from the stream
// it accepted. It is not caller-supplied: the proxy takes the method from the
// stream itself and the namespace from the first request message, so a caller
// cannot forge either by sending a header.
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// full_name is the gRPC full method being invoked, leading slash included, as
	// in "/temporal.api.workflowservice.v1.WorkflowService/DescribeNamespace". It
	// is always set.
	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// namespace is the Temporal namespace the request names. It is empty when the
	// method has no namespace to name, as many do, when the caller sent no message
	// to read one from, or when the proxy does not forward this method's service and
	// so never looked. Empty therefore means "unknown", not "a namespace called
	// nothing": match a namespace-scoped rule against full_name as well, rather than
	// reading empty as a namespace that some rule might accept.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_api_auth_v1_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_target_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Target) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_api_auth_v1_target_proto protoreflect.FileDescriptor

const file_api_auth_v1_target_proto_rawDesc = "" +
	"\n" +
	"\x18api/auth/v1/target.proto\x12\vapi.auth.v1\"C\n" +
	"\x06Target\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespaceB\xa7\x01\n" +
	"\x0fcom.api.auth.v1B\vTargetProtoP\x01Z9github.com/temporalio/temporal-proxy/pkg/api/auth/v1;auth\xa2\x02\x03AAX\xaa\x02\vApi.Auth.V1\xca\x02\vApi\\Auth\\V1\xe2\x02\x17Api\\Auth\\V1\\GPBMetadata\xea\x02\rApi::Auth::V1b\x06proto3"

var (
	file_api_auth_v1_target_proto_rawDescOnce sync.Once
	file_api_auth_v1_target_proto_rawDescData []byte
)

func file_api_auth_v1_target_proto_rawDescGZIP() []byte {
	file_api_auth_v1_target_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_target_proto_rawDesc), len(file_api_auth_v1_target_proto_rawDesc)))
	})
	return file_api_auth_v1_target_proto_rawDescData
}

var file_api_auth_v1_target_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_auth_v1_target_proto_goTypes = []any{
	(*Target)(nil), // 0: api.auth.v1.Target
}
var file_api_auth_v1_target_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_target_proto_init() }
func file_api_auth_v1_target_proto_init() {
	if File_api_auth_v1_target_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_target_proto_rawDesc), len(file_api_auth_v1_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_target_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_target_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_target_proto_msgTypes,
	}.Build()
	File_api_auth_v1_target_proto = out.File
	file_api_auth_v1_target_proto_goTypes = nil
	file_api_auth_v1_target_proto_depIdxs = nil
}
