hostPort: :8444
tls:
  ca: dev/certs/ca.crt
  cert: dev/certs/server.crt
  key: dev/certs/server.key

upstreams:
  - name: default
    hostPort: localhost:7233
    namespaces:
      rules:
        # Always add .remote on the way out, and remove it on the way in.
        suffix: .remote
        overrides:
          # Makes ns2 and ns3 both use ns2.remote on the remote cluster.
          - local: ns3
            remote: ns2.remote

routing:
  default: default
