// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/kms/v1/decrypt.proto

package kms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecryptRequest asks the provider to unwrap ciphertext produced by a prior
// Encrypt call.
type DecryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ciphertext is the wrapped key material to unwrap. It carries whatever the
	// provider needs to locate the key that produced it.
	Ciphertext    []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_api_kms_v1_decrypt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kms_v1_decrypt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_api_kms_v1_decrypt_proto_rawDescGZIP(), []int{0}
}

func (x *DecryptRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// DecryptResponse returns the unwrapped key material.
type DecryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// plaintext is the original key material recovered from the request's
	// ciphertext.
	Plaintext     []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_api_kms_v1_decrypt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kms_v1_decrypt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_api_kms_v1_decrypt_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

var File_api_kms_v1_decrypt_proto protoreflect.FileDescriptor

const file_api_kms_v1_decrypt_proto_rawDesc = "" +
	"\n" +
	"\x18api/kms/v1/decrypt.proto\x12\n" +
	"api.kms.v1\"0\n" +
	"\x0eDecryptRequest\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\"/\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintextB\xa1\x01\n" +
	"\x0ecom.api.kms.v1B\fDecryptProtoP\x01Z7github.com/temporalio/temporal-proxy/pkg/api/kms/v1;kms\xa2\x02\x03AKX\xaa\x02\n" +
	"Api.Kms.V1\xca\x02\n" +
	"Api\\Kms\\V1\xe2\x02\x16Api\\Kms\\V1\\GPBMetadata\xea\x02\fApi::Kms::V1b\x06proto3"

var (
	file_api_kms_v1_decrypt_proto_rawDescOnce sync.Once
	file_api_kms_v1_decrypt_proto_rawDescData []byte
)

func file_api_kms_v1_decrypt_proto_rawDescGZIP() []byte {
	file_api_kms_v1_decrypt_proto_rawDescOnce.Do(func() {
		file_api_kms_v1_decrypt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kms_v1_decrypt_proto_rawDesc), len(file_api_kms_v1_decrypt_proto_rawDesc)))
	})
	return file_api_kms_v1_decrypt_proto_rawDescData
}

var file_api_kms_v1_decrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kms_v1_decrypt_proto_goTypes = []any{
	(*DecryptRequest)(nil),  // 0: api.kms.v1.DecryptRequest
	(*DecryptResponse)(nil), // 1: api.kms.v1.DecryptResponse
}
var file_api_kms_v1_decrypt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kms_v1_decrypt_proto_init() }
func file_api_kms_v1_decrypt_proto_init() {
	if File_api_kms_v1_decrypt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kms_v1_decrypt_proto_rawDesc), len(file_api_kms_v1_decrypt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kms_v1_decrypt_proto_goTypes,
		DependencyIndexes: file_api_kms_v1_decrypt_proto_depIdxs,
		MessageInfos:      file_api_kms_v1_decrypt_proto_msgTypes,
	}.Build()
	File_api_kms_v1_decrypt_proto = out.File
	file_api_kms_v1_decrypt_proto_goTypes = nil
	file_api_kms_v1_decrypt_proto_depIdxs = nil
}
