// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/kms/v1/encrypt.proto

package kms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncryptRequest asks the provider to wrap key material under the key selected
// for the given namespace.
type EncryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is the pre-translation (local) namespace the DEK belongs to. A
	// provider may use it to select a per-namespace wrapping key.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// plaintext is the key material to wrap (a DEK in the proxy's envelope
	// encryption scheme).
	Plaintext     []byte `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_api_kms_v1_encrypt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kms_v1_encrypt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_api_kms_v1_encrypt_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

// EncryptResponse returns the wrapped key material.
type EncryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ciphertext is the wrapped form of the request's plaintext. It should carry
	// whatever the provider needs to later identify the wrapping key, so that
	// Decrypt can unwrap it.
	Ciphertext    []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_api_kms_v1_encrypt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kms_v1_encrypt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_api_kms_v1_encrypt_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_api_kms_v1_encrypt_proto protoreflect.FileDescriptor

const file_api_kms_v1_encrypt_proto_rawDesc = "" +
	"\n" +
	"\x18api/kms/v1/encrypt.proto\x12\n" +
	"api.kms.v1\"L\n" +
	"\x0eEncryptRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\"1\n" +
	"\x0fEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertextB\xa1\x01\n" +
	"\x0ecom.api.kms.v1B\fEncryptProtoP\x01Z7github.com/temporalio/temporal-proxy/pkg/api/kms/v1;kms\xa2\x02\x03AKX\xaa\x02\n" +
	"Api.Kms.V1\xca\x02\n" +
	"Api\\Kms\\V1\xe2\x02\x16Api\\Kms\\V1\\GPBMetadata\xea\x02\fApi::Kms::V1b\x06proto3"

var (
	file_api_kms_v1_encrypt_proto_rawDescOnce sync.Once
	file_api_kms_v1_encrypt_proto_rawDescData []byte
)

func file_api_kms_v1_encrypt_proto_rawDescGZIP() []byte {
	file_api_kms_v1_encrypt_proto_rawDescOnce.Do(func() {
		file_api_kms_v1_encrypt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kms_v1_encrypt_proto_rawDesc), len(file_api_kms_v1_encrypt_proto_rawDesc)))
	})
	return file_api_kms_v1_encrypt_proto_rawDescData
}

var file_api_kms_v1_encrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kms_v1_encrypt_proto_goTypes = []any{
	(*EncryptRequest)(nil),  // 0: api.kms.v1.EncryptRequest
	(*EncryptResponse)(nil), // 1: api.kms.v1.EncryptResponse
}
var file_api_kms_v1_encrypt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kms_v1_encrypt_proto_init() }
func file_api_kms_v1_encrypt_proto_init() {
	if File_api_kms_v1_encrypt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kms_v1_encrypt_proto_rawDesc), len(file_api_kms_v1_encrypt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kms_v1_encrypt_proto_goTypes,
		DependencyIndexes: file_api_kms_v1_encrypt_proto_depIdxs,
		MessageInfos:      file_api_kms_v1_encrypt_proto_msgTypes,
	}.Build()
	File_api_kms_v1_encrypt_proto = out.File
	file_api_kms_v1_encrypt_proto_goTypes = nil
	file_api_kms_v1_encrypt_proto_depIdxs = nil
}
