// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/kms/v1/service.proto

package kms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_kms_v1_service_proto protoreflect.FileDescriptor

const file_api_kms_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18api/kms/v1/service.proto\x12\n" +
	"api.kms.v1\x1a\x18api/kms/v1/decrypt.proto\x1a\x18api/kms/v1/encrypt.proto2\x9f\x01\n" +
	"\x11EncryptionService\x12D\n" +
	"\aEncrypt\x12\x1a.api.kms.v1.EncryptRequest\x1a\x1b.api.kms.v1.EncryptResponse\"\x00\x12D\n" +
	"\aDecrypt\x12\x1a.api.kms.v1.DecryptRequest\x1a\x1b.api.kms.v1.DecryptResponse\"\x00B\xa1\x01\n" +
	"\x0ecom.api.kms.v1B\fServiceProtoP\x01Z7github.com/temporalio/temporal-proxy/pkg/api/kms/v1;kms\xa2\x02\x03AKX\xaa\x02\n" +
	"Api.Kms.V1\xca\x02\n" +
	"Api\\Kms\\V1\xe2\x02\x16Api\\Kms\\V1\\GPBMetadata\xea\x02\fApi::Kms::V1b\x06proto3"

var file_api_kms_v1_service_proto_goTypes = []any{
	(*EncryptRequest)(nil),  // 0: api.kms.v1.EncryptRequest
	(*DecryptRequest)(nil),  // 1: api.kms.v1.DecryptRequest
	(*EncryptResponse)(nil), // 2: api.kms.v1.EncryptResponse
	(*DecryptResponse)(nil), // 3: api.kms.v1.DecryptResponse
}
var file_api_kms_v1_service_proto_depIdxs = []int32{
	0, // 0: api.kms.v1.EncryptionService.Encrypt:input_type -> api.kms.v1.EncryptRequest
	1, // 1: api.kms.v1.EncryptionService.Decrypt:input_type -> api.kms.v1.DecryptRequest
	2, // 2: api.kms.v1.EncryptionService.Encrypt:output_type -> api.kms.v1.EncryptResponse
	3, // 3: api.kms.v1.EncryptionService.Decrypt:output_type -> api.kms.v1.DecryptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kms_v1_service_proto_init() }
func file_api_kms_v1_service_proto_init() {
	if File_api_kms_v1_service_proto != nil {
		return
	}
	file_api_kms_v1_decrypt_proto_init()
	file_api_kms_v1_encrypt_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kms_v1_service_proto_rawDesc), len(file_api_kms_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kms_v1_service_proto_goTypes,
		DependencyIndexes: file_api_kms_v1_service_proto_depIdxs,
	}.Build()
	File_api_kms_v1_service_proto = out.File
	file_api_kms_v1_service_proto_goTypes = nil
	file_api_kms_v1_service_proto_depIdxs = nil
}
