// Package proxy implements Temporal gRPC services that forward every RPC to an
// upstream client.
//
// Each service embeds the API's Unimplemented server and overrides every method
// to relay the request to its upstream client, copying inbound gRPC metadata
// onto the outbound context (see forward). Because every method is an identical
// pass-through, the service implementations and their delegation tests are
// generated by cmd/codegen from the corresponding gRPC server interface; run
// `go generate ./...` after bumping the Temporal API to pick up new RPCs.
package proxy
