// Code generated by MockGen. DO NOT EDIT.
// Source: go.temporal.io/server/api/adminservice/v1 (interfaces: AdminService_StreamWorkflowReplicationMessagesClient,AdminService_StreamWorkflowReplicationMessagesServer)
//
// Generated by this command:
//
//	mockgen -destination forwarder_mocks_test.go -package proxy -typed go.temporal.io/server/api/adminservice/v1 AdminService_StreamWorkflowReplicationMessagesClient,AdminService_StreamWorkflowReplicationMessagesServer
//

// Package proxy is a generated GoMock package.
package proxy

import (
	context "context"
	reflect "reflect"

	adminservice "go.temporal.io/server/api/adminservice/v1"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockAdminService_StreamWorkflowReplicationMessagesClient is a mock of AdminService_StreamWorkflowReplicationMessagesClient interface.
type MockAdminService_StreamWorkflowReplicationMessagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder
	isgomock struct{}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder is the mock recorder for MockAdminService_StreamWorkflowReplicationMessagesClient.
type MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder struct {
	mock *MockAdminService_StreamWorkflowReplicationMessagesClient
}

// NewMockAdminService_StreamWorkflowReplicationMessagesClient creates a new mock instance.
func NewMockAdminService_StreamWorkflowReplicationMessagesClient(ctrl *gomock.Controller) *MockAdminService_StreamWorkflowReplicationMessagesClient {
	mock := &MockAdminService_StreamWorkflowReplicationMessagesClient{ctrl: ctrl}
	mock.recorder = &MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) EXPECT() *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) CloseSend() *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).CloseSend))
	return &MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall) Do(f func() error) *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall) DoAndReturn(f func() error) *MockAdminService_StreamWorkflowReplicationMessagesClientCloseSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Context mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) Context() *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).Context))
	return &MockAdminService_StreamWorkflowReplicationMessagesClientContextCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientContextCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall) Return(arg0 context.Context) *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall) Do(f func() context.Context) *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall) DoAndReturn(f func() context.Context) *MockAdminService_StreamWorkflowReplicationMessagesClientContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Header mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) Header() *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).Header))
	return &MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall) Return(arg0 metadata.MD, arg1 error) *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall) Do(f func() (metadata.MD, error)) *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall) DoAndReturn(f func() (metadata.MD, error)) *MockAdminService_StreamWorkflowReplicationMessagesClientHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Recv mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) Recv() (*adminservice.StreamWorkflowReplicationMessagesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*adminservice.StreamWorkflowReplicationMessagesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) Recv() *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).Recv))
	return &MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall) Return(arg0 *adminservice.StreamWorkflowReplicationMessagesResponse, arg1 error) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall) Do(f func() (*adminservice.StreamWorkflowReplicationMessagesResponse, error)) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall) DoAndReturn(f func() (*adminservice.StreamWorkflowReplicationMessagesResponse, error)) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecvMsg mocks base method.
func (m_2 *MockAdminService_StreamWorkflowReplicationMessagesClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) RecvMsg(m any) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).RecvMsg), m)
	return &MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall) Do(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall) DoAndReturn(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesClientRecvMsgCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) Send(arg0 *adminservice.StreamWorkflowReplicationMessagesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) Send(arg0 any) *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).Send), arg0)
	return &MockAdminService_StreamWorkflowReplicationMessagesClientSendCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientSendCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall) Do(f func(*adminservice.StreamWorkflowReplicationMessagesRequest) error) *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall) DoAndReturn(f func(*adminservice.StreamWorkflowReplicationMessagesRequest) error) *MockAdminService_StreamWorkflowReplicationMessagesClientSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMsg mocks base method.
func (m_2 *MockAdminService_StreamWorkflowReplicationMessagesClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) SendMsg(m any) *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).SendMsg), m)
	return &MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall) Do(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall) DoAndReturn(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesClientSendMsgCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Trailer mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesClientMockRecorder) Trailer() *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesClient)(nil).Trailer))
	return &MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall) Return(arg0 metadata.MD) *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall) Do(f func() metadata.MD) *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall) DoAndReturn(f func() metadata.MD) *MockAdminService_StreamWorkflowReplicationMessagesClientTrailerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAdminService_StreamWorkflowReplicationMessagesServer is a mock of AdminService_StreamWorkflowReplicationMessagesServer interface.
type MockAdminService_StreamWorkflowReplicationMessagesServer struct {
	ctrl     *gomock.Controller
	recorder *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder
	isgomock struct{}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder is the mock recorder for MockAdminService_StreamWorkflowReplicationMessagesServer.
type MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder struct {
	mock *MockAdminService_StreamWorkflowReplicationMessagesServer
}

// NewMockAdminService_StreamWorkflowReplicationMessagesServer creates a new mock instance.
func NewMockAdminService_StreamWorkflowReplicationMessagesServer(ctrl *gomock.Controller) *MockAdminService_StreamWorkflowReplicationMessagesServer {
	mock := &MockAdminService_StreamWorkflowReplicationMessagesServer{ctrl: ctrl}
	mock.recorder = &MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) EXPECT() *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) Context() *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).Context))
	return &MockAdminService_StreamWorkflowReplicationMessagesServerContextCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerContextCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall) Return(arg0 context.Context) *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall) Do(f func() context.Context) *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall) DoAndReturn(f func() context.Context) *MockAdminService_StreamWorkflowReplicationMessagesServerContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Recv mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) Recv() (*adminservice.StreamWorkflowReplicationMessagesRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*adminservice.StreamWorkflowReplicationMessagesRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) Recv() *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).Recv))
	return &MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall) Return(arg0 *adminservice.StreamWorkflowReplicationMessagesRequest, arg1 error) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall) Do(f func() (*adminservice.StreamWorkflowReplicationMessagesRequest, error)) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall) DoAndReturn(f func() (*adminservice.StreamWorkflowReplicationMessagesRequest, error)) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecvMsg mocks base method.
func (m_2 *MockAdminService_StreamWorkflowReplicationMessagesServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) RecvMsg(m any) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).RecvMsg), m)
	return &MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall) Do(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall) DoAndReturn(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesServerRecvMsgCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) Send(arg0 *adminservice.StreamWorkflowReplicationMessagesResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) Send(arg0 any) *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).Send), arg0)
	return &MockAdminService_StreamWorkflowReplicationMessagesServerSendCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerSendCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall) Do(f func(*adminservice.StreamWorkflowReplicationMessagesResponse) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall) DoAndReturn(f func(*adminservice.StreamWorkflowReplicationMessagesResponse) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendHeader mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) SendHeader(arg0 any) *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).SendHeader), arg0)
	return &MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall) Do(f func(metadata.MD) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall) DoAndReturn(f func(metadata.MD) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMsg mocks base method.
func (m_2 *MockAdminService_StreamWorkflowReplicationMessagesServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) SendMsg(m any) *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).SendMsg), m)
	return &MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall) Do(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall) DoAndReturn(f func(any) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSendMsgCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetHeader mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) SetHeader(arg0 any) *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).SetHeader), arg0)
	return &MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall) Return(arg0 error) *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall) Do(f func(metadata.MD) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall) DoAndReturn(f func(metadata.MD) error) *MockAdminService_StreamWorkflowReplicationMessagesServerSetHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetTrailer mocks base method.
func (m *MockAdminService_StreamWorkflowReplicationMessagesServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockAdminService_StreamWorkflowReplicationMessagesServerMockRecorder) SetTrailer(arg0 any) *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockAdminService_StreamWorkflowReplicationMessagesServer)(nil).SetTrailer), arg0)
	return &MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall{Call: call}
}

// MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall wrap *gomock.Call
type MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall) Return() *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall) Do(f func(metadata.MD)) *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall) DoAndReturn(f func(metadata.MD)) *MockAdminService_StreamWorkflowReplicationMessagesServerSetTrailerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
