// Code generated by cmd/codegen. DO NOT EDIT.

package proxy_test

import (
	"reflect"
	"testing"

	"github.com/stretchr/testify/require"
	"go.uber.org/mock/gomock"

	"github.com/temporalio/temporal-proxy/internal/proxy"
)

func TestWorkflowService_DelegatesToClient(t *testing.T) {
	t.Parallel()

	names := rpcMethodNames(reflect.TypeFor[*proxy.WorkflowService]())
	require.NotEmpty(t, names, "expected to discover proxied RPC methods via reflection")

	for _, name := range names {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			ctrl := gomock.NewController(t)
			client := NewMockWorkflowServiceClient(ctrl)
			p := proxy.NewWorkflowService(client)

			method := reflect.ValueOf(p).MethodByName(name)
			require.True(t, method.IsValid(), "method %s not found on proxy", name)

			ft := method.Type()
			req := reflect.New(ft.In(1).Elem())   // *XRequest
			resp := reflect.New(ft.Out(0).Elem()) // *XResponse

			// client.EXPECT().<name>(any, req).Return(resp, nil) -- the exact req
			// pointer is the matcher (gomock.Eq), proving pass-through; the resp
			// pointer is what we expect handed back. Default Times(1) asserts the
			// call happens exactly once.
			recorder := reflect.ValueOf(client.EXPECT()).MethodByName(name)
			require.True(t, recorder.IsValid(), "no recorder for %s on mock client", name)
			call := recorder.Call([]reflect.Value{reflect.ValueOf(gomock.Any()), req})[0]
			call.MethodByName("Return").Call([]reflect.Value{resp, reflect.Zero(errorType)})

			out := method.Call([]reflect.Value{reflect.ValueOf(t.Context()), req})
			require.Same(t, resp.Interface(), out[0].Interface(), "%s did not return the client's response", name)
			require.Nil(t, out[1].Interface(), "%s returned an unexpected error", name)
		})
	}
}
