// Code generated by cmd/codegen. DO NOT EDIT.

package proxy

import (
	"context"

	workflowservice "go.temporal.io/api/workflowservice/v1"
)

// WorkflowService is a WorkflowServiceServer that proxies every RPC to
// an upstream WorkflowServiceClient. Its methods are generated and simply
// forward each request to the client; see cmd/codegen.
type WorkflowService struct {
	workflowservice.UnimplementedWorkflowServiceServer
	client workflowservice.WorkflowServiceClient
}

// NewWorkflowService returns a WorkflowService that forwards all RPCs to client.
func NewWorkflowService(client workflowservice.WorkflowServiceClient) *WorkflowService {
	return &WorkflowService{client: client}
}

func (s *WorkflowService) CountActivityExecutions(
	ctx context.Context,
	req *workflowservice.CountActivityExecutionsRequest,
) (*workflowservice.CountActivityExecutionsResponse, error) {
	return forward(ctx, req, s.client.CountActivityExecutions)
}

func (s *WorkflowService) CountSchedules(
	ctx context.Context,
	req *workflowservice.CountSchedulesRequest,
) (*workflowservice.CountSchedulesResponse, error) {
	return forward(ctx, req, s.client.CountSchedules)
}

func (s *WorkflowService) CountWorkflowExecutions(
	ctx context.Context,
	req *workflowservice.CountWorkflowExecutionsRequest,
) (*workflowservice.CountWorkflowExecutionsResponse, error) {
	return forward(ctx, req, s.client.CountWorkflowExecutions)
}

func (s *WorkflowService) CreateSchedule(
	ctx context.Context,
	req *workflowservice.CreateScheduleRequest,
) (*workflowservice.CreateScheduleResponse, error) {
	return forward(ctx, req, s.client.CreateSchedule)
}

func (s *WorkflowService) CreateWorkerDeployment(
	ctx context.Context,
	req *workflowservice.CreateWorkerDeploymentRequest,
) (*workflowservice.CreateWorkerDeploymentResponse, error) {
	return forward(ctx, req, s.client.CreateWorkerDeployment)
}

func (s *WorkflowService) CreateWorkerDeploymentVersion(
	ctx context.Context,
	req *workflowservice.CreateWorkerDeploymentVersionRequest,
) (*workflowservice.CreateWorkerDeploymentVersionResponse, error) {
	return forward(ctx, req, s.client.CreateWorkerDeploymentVersion)
}

func (s *WorkflowService) CreateWorkflowRule(
	ctx context.Context,
	req *workflowservice.CreateWorkflowRuleRequest,
) (*workflowservice.CreateWorkflowRuleResponse, error) {
	return forward(ctx, req, s.client.CreateWorkflowRule)
}

func (s *WorkflowService) DeleteActivityExecution(
	ctx context.Context,
	req *workflowservice.DeleteActivityExecutionRequest,
) (*workflowservice.DeleteActivityExecutionResponse, error) {
	return forward(ctx, req, s.client.DeleteActivityExecution)
}

func (s *WorkflowService) DeleteSchedule(
	ctx context.Context,
	req *workflowservice.DeleteScheduleRequest,
) (*workflowservice.DeleteScheduleResponse, error) {
	return forward(ctx, req, s.client.DeleteSchedule)
}

func (s *WorkflowService) DeleteWorkerDeployment(
	ctx context.Context,
	req *workflowservice.DeleteWorkerDeploymentRequest,
) (*workflowservice.DeleteWorkerDeploymentResponse, error) {
	return forward(ctx, req, s.client.DeleteWorkerDeployment)
}

func (s *WorkflowService) DeleteWorkerDeploymentVersion(
	ctx context.Context,
	req *workflowservice.DeleteWorkerDeploymentVersionRequest,
) (*workflowservice.DeleteWorkerDeploymentVersionResponse, error) {
	return forward(ctx, req, s.client.DeleteWorkerDeploymentVersion)
}

func (s *WorkflowService) DeleteWorkflowExecution(
	ctx context.Context,
	req *workflowservice.DeleteWorkflowExecutionRequest,
) (*workflowservice.DeleteWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.DeleteWorkflowExecution)
}

func (s *WorkflowService) DeleteWorkflowRule(
	ctx context.Context,
	req *workflowservice.DeleteWorkflowRuleRequest,
) (*workflowservice.DeleteWorkflowRuleResponse, error) {
	return forward(ctx, req, s.client.DeleteWorkflowRule)
}

func (s *WorkflowService) DeprecateNamespace(
	ctx context.Context,
	req *workflowservice.DeprecateNamespaceRequest,
) (*workflowservice.DeprecateNamespaceResponse, error) {
	return forward(ctx, req, s.client.DeprecateNamespace)
}

func (s *WorkflowService) DescribeActivityExecution(
	ctx context.Context,
	req *workflowservice.DescribeActivityExecutionRequest,
) (*workflowservice.DescribeActivityExecutionResponse, error) {
	return forward(ctx, req, s.client.DescribeActivityExecution)
}

func (s *WorkflowService) DescribeBatchOperation(
	ctx context.Context,
	req *workflowservice.DescribeBatchOperationRequest,
) (*workflowservice.DescribeBatchOperationResponse, error) {
	return forward(ctx, req, s.client.DescribeBatchOperation)
}

func (s *WorkflowService) DescribeDeployment(
	ctx context.Context,
	req *workflowservice.DescribeDeploymentRequest,
) (*workflowservice.DescribeDeploymentResponse, error) {
	return forward(ctx, req, s.client.DescribeDeployment)
}

func (s *WorkflowService) DescribeNamespace(
	ctx context.Context,
	req *workflowservice.DescribeNamespaceRequest,
) (*workflowservice.DescribeNamespaceResponse, error) {
	return forward(ctx, req, s.client.DescribeNamespace)
}

func (s *WorkflowService) DescribeSchedule(
	ctx context.Context,
	req *workflowservice.DescribeScheduleRequest,
) (*workflowservice.DescribeScheduleResponse, error) {
	return forward(ctx, req, s.client.DescribeSchedule)
}

func (s *WorkflowService) DescribeTaskQueue(
	ctx context.Context,
	req *workflowservice.DescribeTaskQueueRequest,
) (*workflowservice.DescribeTaskQueueResponse, error) {
	return forward(ctx, req, s.client.DescribeTaskQueue)
}

func (s *WorkflowService) DescribeWorker(
	ctx context.Context,
	req *workflowservice.DescribeWorkerRequest,
) (*workflowservice.DescribeWorkerResponse, error) {
	return forward(ctx, req, s.client.DescribeWorker)
}

func (s *WorkflowService) DescribeWorkerDeployment(
	ctx context.Context,
	req *workflowservice.DescribeWorkerDeploymentRequest,
) (*workflowservice.DescribeWorkerDeploymentResponse, error) {
	return forward(ctx, req, s.client.DescribeWorkerDeployment)
}

func (s *WorkflowService) DescribeWorkerDeploymentVersion(
	ctx context.Context,
	req *workflowservice.DescribeWorkerDeploymentVersionRequest,
) (*workflowservice.DescribeWorkerDeploymentVersionResponse, error) {
	return forward(ctx, req, s.client.DescribeWorkerDeploymentVersion)
}

func (s *WorkflowService) DescribeWorkflowExecution(
	ctx context.Context,
	req *workflowservice.DescribeWorkflowExecutionRequest,
) (*workflowservice.DescribeWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.DescribeWorkflowExecution)
}

func (s *WorkflowService) DescribeWorkflowRule(
	ctx context.Context,
	req *workflowservice.DescribeWorkflowRuleRequest,
) (*workflowservice.DescribeWorkflowRuleResponse, error) {
	return forward(ctx, req, s.client.DescribeWorkflowRule)
}

func (s *WorkflowService) ExecuteMultiOperation(
	ctx context.Context,
	req *workflowservice.ExecuteMultiOperationRequest,
) (*workflowservice.ExecuteMultiOperationResponse, error) {
	return forward(ctx, req, s.client.ExecuteMultiOperation)
}

func (s *WorkflowService) FetchWorkerConfig(
	ctx context.Context,
	req *workflowservice.FetchWorkerConfigRequest,
) (*workflowservice.FetchWorkerConfigResponse, error) {
	return forward(ctx, req, s.client.FetchWorkerConfig)
}

func (s *WorkflowService) GetClusterInfo(
	ctx context.Context,
	req *workflowservice.GetClusterInfoRequest,
) (*workflowservice.GetClusterInfoResponse, error) {
	return forward(ctx, req, s.client.GetClusterInfo)
}

func (s *WorkflowService) GetCurrentDeployment(
	ctx context.Context,
	req *workflowservice.GetCurrentDeploymentRequest,
) (*workflowservice.GetCurrentDeploymentResponse, error) {
	return forward(ctx, req, s.client.GetCurrentDeployment)
}

func (s *WorkflowService) GetDeploymentReachability(
	ctx context.Context,
	req *workflowservice.GetDeploymentReachabilityRequest,
) (*workflowservice.GetDeploymentReachabilityResponse, error) {
	return forward(ctx, req, s.client.GetDeploymentReachability)
}

func (s *WorkflowService) GetSearchAttributes(
	ctx context.Context,
	req *workflowservice.GetSearchAttributesRequest,
) (*workflowservice.GetSearchAttributesResponse, error) {
	return forward(ctx, req, s.client.GetSearchAttributes)
}

func (s *WorkflowService) GetSystemInfo(
	ctx context.Context,
	req *workflowservice.GetSystemInfoRequest,
) (*workflowservice.GetSystemInfoResponse, error) {
	return forward(ctx, req, s.client.GetSystemInfo)
}

func (s *WorkflowService) GetWorkerBuildIdCompatibility(
	ctx context.Context,
	req *workflowservice.GetWorkerBuildIdCompatibilityRequest,
) (*workflowservice.GetWorkerBuildIdCompatibilityResponse, error) {
	return forward(ctx, req, s.client.GetWorkerBuildIdCompatibility)
}

func (s *WorkflowService) GetWorkerTaskReachability(
	ctx context.Context,
	req *workflowservice.GetWorkerTaskReachabilityRequest,
) (*workflowservice.GetWorkerTaskReachabilityResponse, error) {
	return forward(ctx, req, s.client.GetWorkerTaskReachability)
}

func (s *WorkflowService) GetWorkerVersioningRules(
	ctx context.Context,
	req *workflowservice.GetWorkerVersioningRulesRequest,
) (*workflowservice.GetWorkerVersioningRulesResponse, error) {
	return forward(ctx, req, s.client.GetWorkerVersioningRules)
}

func (s *WorkflowService) GetWorkflowExecutionHistory(
	ctx context.Context,
	req *workflowservice.GetWorkflowExecutionHistoryRequest,
) (*workflowservice.GetWorkflowExecutionHistoryResponse, error) {
	return forward(ctx, req, s.client.GetWorkflowExecutionHistory)
}

func (s *WorkflowService) GetWorkflowExecutionHistoryReverse(
	ctx context.Context,
	req *workflowservice.GetWorkflowExecutionHistoryReverseRequest,
) (*workflowservice.GetWorkflowExecutionHistoryReverseResponse, error) {
	return forward(ctx, req, s.client.GetWorkflowExecutionHistoryReverse)
}

func (s *WorkflowService) ListActivityExecutions(
	ctx context.Context,
	req *workflowservice.ListActivityExecutionsRequest,
) (*workflowservice.ListActivityExecutionsResponse, error) {
	return forward(ctx, req, s.client.ListActivityExecutions)
}

func (s *WorkflowService) ListArchivedWorkflowExecutions(
	ctx context.Context,
	req *workflowservice.ListArchivedWorkflowExecutionsRequest,
) (*workflowservice.ListArchivedWorkflowExecutionsResponse, error) {
	return forward(ctx, req, s.client.ListArchivedWorkflowExecutions)
}

func (s *WorkflowService) ListBatchOperations(
	ctx context.Context,
	req *workflowservice.ListBatchOperationsRequest,
) (*workflowservice.ListBatchOperationsResponse, error) {
	return forward(ctx, req, s.client.ListBatchOperations)
}

func (s *WorkflowService) ListClosedWorkflowExecutions(
	ctx context.Context,
	req *workflowservice.ListClosedWorkflowExecutionsRequest,
) (*workflowservice.ListClosedWorkflowExecutionsResponse, error) {
	return forward(ctx, req, s.client.ListClosedWorkflowExecutions)
}

func (s *WorkflowService) ListDeployments(
	ctx context.Context,
	req *workflowservice.ListDeploymentsRequest,
) (*workflowservice.ListDeploymentsResponse, error) {
	return forward(ctx, req, s.client.ListDeployments)
}

func (s *WorkflowService) ListNamespaces(
	ctx context.Context,
	req *workflowservice.ListNamespacesRequest,
) (*workflowservice.ListNamespacesResponse, error) {
	return forward(ctx, req, s.client.ListNamespaces)
}

func (s *WorkflowService) ListOpenWorkflowExecutions(
	ctx context.Context,
	req *workflowservice.ListOpenWorkflowExecutionsRequest,
) (*workflowservice.ListOpenWorkflowExecutionsResponse, error) {
	return forward(ctx, req, s.client.ListOpenWorkflowExecutions)
}

func (s *WorkflowService) ListScheduleMatchingTimes(
	ctx context.Context,
	req *workflowservice.ListScheduleMatchingTimesRequest,
) (*workflowservice.ListScheduleMatchingTimesResponse, error) {
	return forward(ctx, req, s.client.ListScheduleMatchingTimes)
}

func (s *WorkflowService) ListSchedules(
	ctx context.Context,
	req *workflowservice.ListSchedulesRequest,
) (*workflowservice.ListSchedulesResponse, error) {
	return forward(ctx, req, s.client.ListSchedules)
}

func (s *WorkflowService) ListTaskQueuePartitions(
	ctx context.Context,
	req *workflowservice.ListTaskQueuePartitionsRequest,
) (*workflowservice.ListTaskQueuePartitionsResponse, error) {
	return forward(ctx, req, s.client.ListTaskQueuePartitions)
}

func (s *WorkflowService) ListWorkerDeployments(
	ctx context.Context,
	req *workflowservice.ListWorkerDeploymentsRequest,
) (*workflowservice.ListWorkerDeploymentsResponse, error) {
	return forward(ctx, req, s.client.ListWorkerDeployments)
}

func (s *WorkflowService) ListWorkers(
	ctx context.Context,
	req *workflowservice.ListWorkersRequest,
) (*workflowservice.ListWorkersResponse, error) {
	return forward(ctx, req, s.client.ListWorkers)
}

func (s *WorkflowService) ListWorkflowExecutions(
	ctx context.Context,
	req *workflowservice.ListWorkflowExecutionsRequest,
) (*workflowservice.ListWorkflowExecutionsResponse, error) {
	return forward(ctx, req, s.client.ListWorkflowExecutions)
}

func (s *WorkflowService) ListWorkflowRules(
	ctx context.Context,
	req *workflowservice.ListWorkflowRulesRequest,
) (*workflowservice.ListWorkflowRulesResponse, error) {
	return forward(ctx, req, s.client.ListWorkflowRules)
}

func (s *WorkflowService) PatchSchedule(
	ctx context.Context,
	req *workflowservice.PatchScheduleRequest,
) (*workflowservice.PatchScheduleResponse, error) {
	return forward(ctx, req, s.client.PatchSchedule)
}

func (s *WorkflowService) PauseActivity(
	ctx context.Context,
	req *workflowservice.PauseActivityRequest,
) (*workflowservice.PauseActivityResponse, error) {
	return forward(ctx, req, s.client.PauseActivity)
}

func (s *WorkflowService) PauseWorkflowExecution(
	ctx context.Context,
	req *workflowservice.PauseWorkflowExecutionRequest,
) (*workflowservice.PauseWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.PauseWorkflowExecution)
}

func (s *WorkflowService) PollActivityExecution(
	ctx context.Context,
	req *workflowservice.PollActivityExecutionRequest,
) (*workflowservice.PollActivityExecutionResponse, error) {
	return forward(ctx, req, s.client.PollActivityExecution)
}

func (s *WorkflowService) PollActivityTaskQueue(
	ctx context.Context,
	req *workflowservice.PollActivityTaskQueueRequest,
) (*workflowservice.PollActivityTaskQueueResponse, error) {
	return forward(ctx, req, s.client.PollActivityTaskQueue)
}

func (s *WorkflowService) PollNexusTaskQueue(
	ctx context.Context,
	req *workflowservice.PollNexusTaskQueueRequest,
) (*workflowservice.PollNexusTaskQueueResponse, error) {
	return forward(ctx, req, s.client.PollNexusTaskQueue)
}

func (s *WorkflowService) PollWorkflowExecutionUpdate(
	ctx context.Context,
	req *workflowservice.PollWorkflowExecutionUpdateRequest,
) (*workflowservice.PollWorkflowExecutionUpdateResponse, error) {
	return forward(ctx, req, s.client.PollWorkflowExecutionUpdate)
}

func (s *WorkflowService) PollWorkflowTaskQueue(
	ctx context.Context,
	req *workflowservice.PollWorkflowTaskQueueRequest,
) (*workflowservice.PollWorkflowTaskQueueResponse, error) {
	return forward(ctx, req, s.client.PollWorkflowTaskQueue)
}

func (s *WorkflowService) QueryWorkflow(
	ctx context.Context,
	req *workflowservice.QueryWorkflowRequest,
) (*workflowservice.QueryWorkflowResponse, error) {
	return forward(ctx, req, s.client.QueryWorkflow)
}

func (s *WorkflowService) RecordActivityTaskHeartbeat(
	ctx context.Context,
	req *workflowservice.RecordActivityTaskHeartbeatRequest,
) (*workflowservice.RecordActivityTaskHeartbeatResponse, error) {
	return forward(ctx, req, s.client.RecordActivityTaskHeartbeat)
}

func (s *WorkflowService) RecordActivityTaskHeartbeatById(
	ctx context.Context,
	req *workflowservice.RecordActivityTaskHeartbeatByIdRequest,
) (*workflowservice.RecordActivityTaskHeartbeatByIdResponse, error) {
	return forward(ctx, req, s.client.RecordActivityTaskHeartbeatById)
}

func (s *WorkflowService) RecordWorkerHeartbeat(
	ctx context.Context,
	req *workflowservice.RecordWorkerHeartbeatRequest,
) (*workflowservice.RecordWorkerHeartbeatResponse, error) {
	return forward(ctx, req, s.client.RecordWorkerHeartbeat)
}

func (s *WorkflowService) RegisterNamespace(
	ctx context.Context,
	req *workflowservice.RegisterNamespaceRequest,
) (*workflowservice.RegisterNamespaceResponse, error) {
	return forward(ctx, req, s.client.RegisterNamespace)
}

func (s *WorkflowService) RequestCancelActivityExecution(
	ctx context.Context,
	req *workflowservice.RequestCancelActivityExecutionRequest,
) (*workflowservice.RequestCancelActivityExecutionResponse, error) {
	return forward(ctx, req, s.client.RequestCancelActivityExecution)
}

func (s *WorkflowService) RequestCancelWorkflowExecution(
	ctx context.Context,
	req *workflowservice.RequestCancelWorkflowExecutionRequest,
) (*workflowservice.RequestCancelWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.RequestCancelWorkflowExecution)
}

func (s *WorkflowService) ResetActivity(
	ctx context.Context,
	req *workflowservice.ResetActivityRequest,
) (*workflowservice.ResetActivityResponse, error) {
	return forward(ctx, req, s.client.ResetActivity)
}

func (s *WorkflowService) ResetStickyTaskQueue(
	ctx context.Context,
	req *workflowservice.ResetStickyTaskQueueRequest,
) (*workflowservice.ResetStickyTaskQueueResponse, error) {
	return forward(ctx, req, s.client.ResetStickyTaskQueue)
}

func (s *WorkflowService) ResetWorkflowExecution(
	ctx context.Context,
	req *workflowservice.ResetWorkflowExecutionRequest,
) (*workflowservice.ResetWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.ResetWorkflowExecution)
}

func (s *WorkflowService) RespondActivityTaskCanceled(
	ctx context.Context,
	req *workflowservice.RespondActivityTaskCanceledRequest,
) (*workflowservice.RespondActivityTaskCanceledResponse, error) {
	return forward(ctx, req, s.client.RespondActivityTaskCanceled)
}

func (s *WorkflowService) RespondActivityTaskCanceledById(
	ctx context.Context,
	req *workflowservice.RespondActivityTaskCanceledByIdRequest,
) (*workflowservice.RespondActivityTaskCanceledByIdResponse, error) {
	return forward(ctx, req, s.client.RespondActivityTaskCanceledById)
}

func (s *WorkflowService) RespondActivityTaskCompleted(
	ctx context.Context,
	req *workflowservice.RespondActivityTaskCompletedRequest,
) (*workflowservice.RespondActivityTaskCompletedResponse, error) {
	return forward(ctx, req, s.client.RespondActivityTaskCompleted)
}

func (s *WorkflowService) RespondActivityTaskCompletedById(
	ctx context.Context,
	req *workflowservice.RespondActivityTaskCompletedByIdRequest,
) (*workflowservice.RespondActivityTaskCompletedByIdResponse, error) {
	return forward(ctx, req, s.client.RespondActivityTaskCompletedById)
}

func (s *WorkflowService) RespondActivityTaskFailed(
	ctx context.Context,
	req *workflowservice.RespondActivityTaskFailedRequest,
) (*workflowservice.RespondActivityTaskFailedResponse, error) {
	return forward(ctx, req, s.client.RespondActivityTaskFailed)
}

func (s *WorkflowService) RespondActivityTaskFailedById(
	ctx context.Context,
	req *workflowservice.RespondActivityTaskFailedByIdRequest,
) (*workflowservice.RespondActivityTaskFailedByIdResponse, error) {
	return forward(ctx, req, s.client.RespondActivityTaskFailedById)
}

func (s *WorkflowService) RespondNexusTaskCompleted(
	ctx context.Context,
	req *workflowservice.RespondNexusTaskCompletedRequest,
) (*workflowservice.RespondNexusTaskCompletedResponse, error) {
	return forward(ctx, req, s.client.RespondNexusTaskCompleted)
}

func (s *WorkflowService) RespondNexusTaskFailed(
	ctx context.Context,
	req *workflowservice.RespondNexusTaskFailedRequest,
) (*workflowservice.RespondNexusTaskFailedResponse, error) {
	return forward(ctx, req, s.client.RespondNexusTaskFailed)
}

func (s *WorkflowService) RespondQueryTaskCompleted(
	ctx context.Context,
	req *workflowservice.RespondQueryTaskCompletedRequest,
) (*workflowservice.RespondQueryTaskCompletedResponse, error) {
	return forward(ctx, req, s.client.RespondQueryTaskCompleted)
}

func (s *WorkflowService) RespondWorkflowTaskCompleted(
	ctx context.Context,
	req *workflowservice.RespondWorkflowTaskCompletedRequest,
) (*workflowservice.RespondWorkflowTaskCompletedResponse, error) {
	return forward(ctx, req, s.client.RespondWorkflowTaskCompleted)
}

func (s *WorkflowService) RespondWorkflowTaskFailed(
	ctx context.Context,
	req *workflowservice.RespondWorkflowTaskFailedRequest,
) (*workflowservice.RespondWorkflowTaskFailedResponse, error) {
	return forward(ctx, req, s.client.RespondWorkflowTaskFailed)
}

func (s *WorkflowService) ScanWorkflowExecutions(
	ctx context.Context,
	req *workflowservice.ScanWorkflowExecutionsRequest,
) (*workflowservice.ScanWorkflowExecutionsResponse, error) {
	return forward(ctx, req, s.client.ScanWorkflowExecutions)
}

func (s *WorkflowService) SetCurrentDeployment(
	ctx context.Context,
	req *workflowservice.SetCurrentDeploymentRequest,
) (*workflowservice.SetCurrentDeploymentResponse, error) {
	return forward(ctx, req, s.client.SetCurrentDeployment)
}

func (s *WorkflowService) SetWorkerDeploymentCurrentVersion(
	ctx context.Context,
	req *workflowservice.SetWorkerDeploymentCurrentVersionRequest,
) (*workflowservice.SetWorkerDeploymentCurrentVersionResponse, error) {
	return forward(ctx, req, s.client.SetWorkerDeploymentCurrentVersion)
}

func (s *WorkflowService) SetWorkerDeploymentManager(
	ctx context.Context,
	req *workflowservice.SetWorkerDeploymentManagerRequest,
) (*workflowservice.SetWorkerDeploymentManagerResponse, error) {
	return forward(ctx, req, s.client.SetWorkerDeploymentManager)
}

func (s *WorkflowService) SetWorkerDeploymentRampingVersion(
	ctx context.Context,
	req *workflowservice.SetWorkerDeploymentRampingVersionRequest,
) (*workflowservice.SetWorkerDeploymentRampingVersionResponse, error) {
	return forward(ctx, req, s.client.SetWorkerDeploymentRampingVersion)
}

func (s *WorkflowService) ShutdownWorker(
	ctx context.Context,
	req *workflowservice.ShutdownWorkerRequest,
) (*workflowservice.ShutdownWorkerResponse, error) {
	return forward(ctx, req, s.client.ShutdownWorker)
}

func (s *WorkflowService) SignalWithStartWorkflowExecution(
	ctx context.Context,
	req *workflowservice.SignalWithStartWorkflowExecutionRequest,
) (*workflowservice.SignalWithStartWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.SignalWithStartWorkflowExecution)
}

func (s *WorkflowService) SignalWorkflowExecution(
	ctx context.Context,
	req *workflowservice.SignalWorkflowExecutionRequest,
) (*workflowservice.SignalWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.SignalWorkflowExecution)
}

func (s *WorkflowService) StartActivityExecution(
	ctx context.Context,
	req *workflowservice.StartActivityExecutionRequest,
) (*workflowservice.StartActivityExecutionResponse, error) {
	return forward(ctx, req, s.client.StartActivityExecution)
}

func (s *WorkflowService) StartBatchOperation(
	ctx context.Context,
	req *workflowservice.StartBatchOperationRequest,
) (*workflowservice.StartBatchOperationResponse, error) {
	return forward(ctx, req, s.client.StartBatchOperation)
}

func (s *WorkflowService) StartWorkflowExecution(
	ctx context.Context,
	req *workflowservice.StartWorkflowExecutionRequest,
) (*workflowservice.StartWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.StartWorkflowExecution)
}

func (s *WorkflowService) StopBatchOperation(
	ctx context.Context,
	req *workflowservice.StopBatchOperationRequest,
) (*workflowservice.StopBatchOperationResponse, error) {
	return forward(ctx, req, s.client.StopBatchOperation)
}

func (s *WorkflowService) TerminateActivityExecution(
	ctx context.Context,
	req *workflowservice.TerminateActivityExecutionRequest,
) (*workflowservice.TerminateActivityExecutionResponse, error) {
	return forward(ctx, req, s.client.TerminateActivityExecution)
}

func (s *WorkflowService) TerminateWorkflowExecution(
	ctx context.Context,
	req *workflowservice.TerminateWorkflowExecutionRequest,
) (*workflowservice.TerminateWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.TerminateWorkflowExecution)
}

func (s *WorkflowService) TriggerWorkflowRule(
	ctx context.Context,
	req *workflowservice.TriggerWorkflowRuleRequest,
) (*workflowservice.TriggerWorkflowRuleResponse, error) {
	return forward(ctx, req, s.client.TriggerWorkflowRule)
}

func (s *WorkflowService) UnpauseActivity(
	ctx context.Context,
	req *workflowservice.UnpauseActivityRequest,
) (*workflowservice.UnpauseActivityResponse, error) {
	return forward(ctx, req, s.client.UnpauseActivity)
}

func (s *WorkflowService) UnpauseWorkflowExecution(
	ctx context.Context,
	req *workflowservice.UnpauseWorkflowExecutionRequest,
) (*workflowservice.UnpauseWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.UnpauseWorkflowExecution)
}

func (s *WorkflowService) UpdateActivityOptions(
	ctx context.Context,
	req *workflowservice.UpdateActivityOptionsRequest,
) (*workflowservice.UpdateActivityOptionsResponse, error) {
	return forward(ctx, req, s.client.UpdateActivityOptions)
}

func (s *WorkflowService) UpdateNamespace(
	ctx context.Context,
	req *workflowservice.UpdateNamespaceRequest,
) (*workflowservice.UpdateNamespaceResponse, error) {
	return forward(ctx, req, s.client.UpdateNamespace)
}

func (s *WorkflowService) UpdateSchedule(
	ctx context.Context,
	req *workflowservice.UpdateScheduleRequest,
) (*workflowservice.UpdateScheduleResponse, error) {
	return forward(ctx, req, s.client.UpdateSchedule)
}

func (s *WorkflowService) UpdateTaskQueueConfig(
	ctx context.Context,
	req *workflowservice.UpdateTaskQueueConfigRequest,
) (*workflowservice.UpdateTaskQueueConfigResponse, error) {
	return forward(ctx, req, s.client.UpdateTaskQueueConfig)
}

func (s *WorkflowService) UpdateWorkerBuildIdCompatibility(
	ctx context.Context,
	req *workflowservice.UpdateWorkerBuildIdCompatibilityRequest,
) (*workflowservice.UpdateWorkerBuildIdCompatibilityResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkerBuildIdCompatibility)
}

func (s *WorkflowService) UpdateWorkerConfig(
	ctx context.Context,
	req *workflowservice.UpdateWorkerConfigRequest,
) (*workflowservice.UpdateWorkerConfigResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkerConfig)
}

func (s *WorkflowService) UpdateWorkerDeploymentVersionComputeConfig(
	ctx context.Context,
	req *workflowservice.UpdateWorkerDeploymentVersionComputeConfigRequest,
) (*workflowservice.UpdateWorkerDeploymentVersionComputeConfigResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkerDeploymentVersionComputeConfig)
}

func (s *WorkflowService) UpdateWorkerDeploymentVersionMetadata(
	ctx context.Context,
	req *workflowservice.UpdateWorkerDeploymentVersionMetadataRequest,
) (*workflowservice.UpdateWorkerDeploymentVersionMetadataResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkerDeploymentVersionMetadata)
}

func (s *WorkflowService) UpdateWorkerVersioningRules(
	ctx context.Context,
	req *workflowservice.UpdateWorkerVersioningRulesRequest,
) (*workflowservice.UpdateWorkerVersioningRulesResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkerVersioningRules)
}

func (s *WorkflowService) UpdateWorkflowExecution(
	ctx context.Context,
	req *workflowservice.UpdateWorkflowExecutionRequest,
) (*workflowservice.UpdateWorkflowExecutionResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkflowExecution)
}

func (s *WorkflowService) UpdateWorkflowExecutionOptions(
	ctx context.Context,
	req *workflowservice.UpdateWorkflowExecutionOptionsRequest,
) (*workflowservice.UpdateWorkflowExecutionOptionsResponse, error) {
	return forward(ctx, req, s.client.UpdateWorkflowExecutionOptions)
}

func (s *WorkflowService) ValidateWorkerDeploymentVersionComputeConfig(
	ctx context.Context,
	req *workflowservice.ValidateWorkerDeploymentVersionComputeConfigRequest,
) (*workflowservice.ValidateWorkerDeploymentVersionComputeConfigResponse, error) {
	return forward(ctx, req, s.client.ValidateWorkerDeploymentVersionComputeConfig)
}
