// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/ext/v1/key_material.proto

package ext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyMaterial is an optional framing for the ciphertext an extension server
// returns from Encrypt. Decrypt is handed nothing but that ciphertext, so
// anything the server needs to find the wrapping key again has to travel inside
// it. Rather than hand-roll a binary frame, a server can marshal this message as
// its ciphertext and unmarshal it on the way back.
//
// The fields other than encrypted_dek are metadata in the clear: this is
// framing, not encryption. A namespace is not a secret (it already travels in
// gRPC metadata), but a server that would rather not expose one can leave
// namespace empty and identify its key through opaque instead.
//
// Every byte of this message rides in the metadata of each payload it seals,
// and stays there for as long as the Workflow retention period. Carry what
// decrypt needs to find the key, and nothing else.
type KeyMaterial struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// encrypted_dek is the wrapped DEK, as produced by whatever wrapping the
	// extension server performs. It is the one field that must be set.
	EncryptedDek []byte `protobuf:"bytes,1,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"`
	// version identifies which version of the wrapping key sealed
	// encrypted_dek, so a server that rotates key material can select the same
	// version again on decrypt. Empty means the server does not version its
	// keys.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// namespace is the pre-translation (local) namespace the DEK belongs to,
	// copied from EncryptRequest.namespace. A server that derives a key per
	// namespace needs it to derive the same key on decrypt, where the request no
	// longer carries it. Empty means the server does not key off the namespace.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// opaque belongs to the extension server. Neither the proxy nor this message
	// gives it any meaning: it is round-tripped untouched, so a server that needs
	// more than version and namespace to find its key can put its own encoding
	// here instead of replacing this framing wholesale. Whatever goes in owns its
	// own compatibility, since the proxy cannot migrate what it cannot read.
	Opaque        []byte `protobuf:"bytes,4,opt,name=opaque,proto3" json:"opaque,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyMaterial) Reset() {
	*x = KeyMaterial{}
	mi := &file_api_ext_v1_key_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMaterial) ProtoMessage() {}

func (x *KeyMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_api_ext_v1_key_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMaterial.ProtoReflect.Descriptor instead.
func (*KeyMaterial) Descriptor() ([]byte, []int) {
	return file_api_ext_v1_key_material_proto_rawDescGZIP(), []int{0}
}

func (x *KeyMaterial) GetEncryptedDek() []byte {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *KeyMaterial) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KeyMaterial) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KeyMaterial) GetOpaque() []byte {
	if x != nil {
		return x.Opaque
	}
	return nil
}

var File_api_ext_v1_key_material_proto protoreflect.FileDescriptor

const file_api_ext_v1_key_material_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/ext/v1/key_material.proto\x12\n" +
	"api.ext.v1\"\x82\x01\n" +
	"\vKeyMaterial\x12#\n" +
	"\rencrypted_dek\x18\x01 \x01(\fR\fencryptedDek\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06opaque\x18\x04 \x01(\fR\x06opaqueB\xa5\x01\n" +
	"\x0ecom.api.ext.v1B\x10KeyMaterialProtoP\x01Z7github.com/temporalio/temporal-proxy/pkg/api/ext/v1;ext\xa2\x02\x03AEX\xaa\x02\n" +
	"Api.Ext.V1\xca\x02\n" +
	"Api\\Ext\\V1\xe2\x02\x16Api\\Ext\\V1\\GPBMetadata\xea\x02\fApi::Ext::V1b\x06proto3"

var (
	file_api_ext_v1_key_material_proto_rawDescOnce sync.Once
	file_api_ext_v1_key_material_proto_rawDescData []byte
)

func file_api_ext_v1_key_material_proto_rawDescGZIP() []byte {
	file_api_ext_v1_key_material_proto_rawDescOnce.Do(func() {
		file_api_ext_v1_key_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ext_v1_key_material_proto_rawDesc), len(file_api_ext_v1_key_material_proto_rawDesc)))
	})
	return file_api_ext_v1_key_material_proto_rawDescData
}

var file_api_ext_v1_key_material_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_ext_v1_key_material_proto_goTypes = []any{
	(*KeyMaterial)(nil), // 0: api.ext.v1.KeyMaterial
}
var file_api_ext_v1_key_material_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ext_v1_key_material_proto_init() }
func file_api_ext_v1_key_material_proto_init() {
	if File_api_ext_v1_key_material_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ext_v1_key_material_proto_rawDesc), len(file_api_ext_v1_key_material_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_ext_v1_key_material_proto_goTypes,
		DependencyIndexes: file_api_ext_v1_key_material_proto_depIdxs,
		MessageInfos:      file_api_ext_v1_key_material_proto_msgTypes,
	}.Build()
	File_api_ext_v1_key_material_proto = out.File
	file_api_ext_v1_key_material_proto_goTypes = nil
	file_api_ext_v1_key_material_proto_depIdxs = nil
}
