// Code generated by cmd/codegen. DO NOT EDIT.

// Field visitors for visit. Map iteration order is not deterministic,
// so callbacks for fields stored in maps may run in any order.

package visit

import (
	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	proto "google.golang.org/protobuf/proto"
)

// DataBlobs invokes cb for every common.DataBlob reachable in msg. It returns
// true if msg was a recognized request or response type.
func DataBlobs(msg proto.Message, cb func(*common.DataBlob) error) (bool, error) {
	switch m := msg.(type) {
	case *workflowservice.GetWorkflowExecutionHistoryResponse:
		return true, visitDataBlobs_workflowservice_GetWorkflowExecutionHistoryResponse(m, cb)
	default:
		return false, nil
	}
}

func visitDataBlobs_workflowservice_GetWorkflowExecutionHistoryResponse(m *workflowservice.GetWorkflowExecutionHistoryResponse, cb func(*common.DataBlob) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetRawHistory() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}
