// Code generated by cmd/codegen. DO NOT EDIT.

package visit_test

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"

	"github.com/temporalio/temporal-proxy/internal/visit"
	"github.com/temporalio/temporal-proxy/internal/visit/visitcheck"
)

func TestDataBlobs_GetWorkflowExecutionHistoryResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetWorkflowExecutionHistoryResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.DataBlob
			handled, err := visit.DataBlobs(variant, func(p *common.DataBlob) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.DataBlob{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}
