// Code generated by cmd/codegen. DO NOT EDIT.

// Field visitors for visit. Map iteration order is not deterministic,
// so callbacks for fields stored in maps may run in any order.

package visit

import (
	command "go.temporal.io/api/command/v1"
	common "go.temporal.io/api/common/v1"
	history "go.temporal.io/api/history/v1"
	schedule "go.temporal.io/api/schedule/v1"
	workflow "go.temporal.io/api/workflow/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	proto "google.golang.org/protobuf/proto"
)

// Memos invokes cb for every common.Memo reachable in msg. It returns
// true if msg was a recognized request or response type.
func Memos(msg proto.Message, cb func(*common.Memo) error) (bool, error) {
	switch m := msg.(type) {
	case *workflowservice.CreateScheduleRequest:
		return true, visitMemos_workflowservice_CreateScheduleRequest(m, cb)
	case *workflowservice.DescribeScheduleResponse:
		return true, visitMemos_workflowservice_DescribeScheduleResponse(m, cb)
	case *workflowservice.DescribeWorkflowExecutionResponse:
		return true, visitMemos_workflowservice_DescribeWorkflowExecutionResponse(m, cb)
	case *workflowservice.ExecuteMultiOperationRequest:
		return true, visitMemos_workflowservice_ExecuteMultiOperationRequest(m, cb)
	case *workflowservice.ExecuteMultiOperationResponse:
		return true, visitMemos_workflowservice_ExecuteMultiOperationResponse(m, cb)
	case *workflowservice.GetWorkflowExecutionHistoryResponse:
		return true, visitMemos_workflowservice_GetWorkflowExecutionHistoryResponse(m, cb)
	case *workflowservice.GetWorkflowExecutionHistoryReverseResponse:
		return true, visitMemos_workflowservice_GetWorkflowExecutionHistoryReverseResponse(m, cb)
	case *workflowservice.ListArchivedWorkflowExecutionsResponse:
		return true, visitMemos_workflowservice_ListArchivedWorkflowExecutionsResponse(m, cb)
	case *workflowservice.ListClosedWorkflowExecutionsResponse:
		return true, visitMemos_workflowservice_ListClosedWorkflowExecutionsResponse(m, cb)
	case *workflowservice.ListOpenWorkflowExecutionsResponse:
		return true, visitMemos_workflowservice_ListOpenWorkflowExecutionsResponse(m, cb)
	case *workflowservice.ListSchedulesResponse:
		return true, visitMemos_workflowservice_ListSchedulesResponse(m, cb)
	case *workflowservice.ListWorkflowExecutionsResponse:
		return true, visitMemos_workflowservice_ListWorkflowExecutionsResponse(m, cb)
	case *workflowservice.PollWorkflowTaskQueueResponse:
		return true, visitMemos_workflowservice_PollWorkflowTaskQueueResponse(m, cb)
	case *workflowservice.RespondWorkflowTaskCompletedRequest:
		return true, visitMemos_workflowservice_RespondWorkflowTaskCompletedRequest(m, cb)
	case *workflowservice.RespondWorkflowTaskCompletedResponse:
		return true, visitMemos_workflowservice_RespondWorkflowTaskCompletedResponse(m, cb)
	case *workflowservice.ScanWorkflowExecutionsResponse:
		return true, visitMemos_workflowservice_ScanWorkflowExecutionsResponse(m, cb)
	case *workflowservice.SignalWithStartWorkflowExecutionRequest:
		return true, visitMemos_workflowservice_SignalWithStartWorkflowExecutionRequest(m, cb)
	case *workflowservice.StartWorkflowExecutionRequest:
		return true, visitMemos_workflowservice_StartWorkflowExecutionRequest(m, cb)
	case *workflowservice.StartWorkflowExecutionResponse:
		return true, visitMemos_workflowservice_StartWorkflowExecutionResponse(m, cb)
	case *workflowservice.UpdateScheduleRequest:
		return true, visitMemos_workflowservice_UpdateScheduleRequest(m, cb)
	default:
		return false, nil
	}
}

func visitMemos_command_Command(m *command.Command, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetContinueAsNewWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitMemos_command_ContinueAsNewWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetModifyWorkflowPropertiesCommandAttributes(); v != nil {
		if err := visitMemos_command_ModifyWorkflowPropertiesCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetStartChildWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitMemos_command_StartChildWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_command_ContinueAsNewWorkflowExecutionCommandAttributes(m *command.ContinueAsNewWorkflowExecutionCommandAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_command_ModifyWorkflowPropertiesCommandAttributes(m *command.ModifyWorkflowPropertiesCommandAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpsertedMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_command_StartChildWorkflowExecutionCommandAttributes(m *command.StartChildWorkflowExecutionCommandAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_history_History(m *history.History, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetEvents() {
		if v != nil {
			if err := visitMemos_history_HistoryEvent(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_history_HistoryEvent(m *history.HistoryEvent, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartChildWorkflowExecutionInitiatedEventAttributes(); v != nil {
		if err := visitMemos_history_StartChildWorkflowExecutionInitiatedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionContinuedAsNewEventAttributes(); v != nil {
		if err := visitMemos_history_WorkflowExecutionContinuedAsNewEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionStartedEventAttributes(); v != nil {
		if err := visitMemos_history_WorkflowExecutionStartedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowPropertiesModifiedEventAttributes(); v != nil {
		if err := visitMemos_history_WorkflowPropertiesModifiedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowPropertiesModifiedExternallyEventAttributes(); v != nil {
		if err := visitMemos_history_WorkflowPropertiesModifiedExternallyEventAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_history_StartChildWorkflowExecutionInitiatedEventAttributes(m *history.StartChildWorkflowExecutionInitiatedEventAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_history_WorkflowExecutionContinuedAsNewEventAttributes(m *history.WorkflowExecutionContinuedAsNewEventAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_history_WorkflowExecutionStartedEventAttributes(m *history.WorkflowExecutionStartedEventAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_history_WorkflowPropertiesModifiedEventAttributes(m *history.WorkflowPropertiesModifiedEventAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpsertedMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_history_WorkflowPropertiesModifiedExternallyEventAttributes(m *history.WorkflowPropertiesModifiedExternallyEventAttributes, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpsertedMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_schedule_Schedule(m *schedule.Schedule, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetAction(); v != nil {
		if err := visitMemos_schedule_ScheduleAction(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_schedule_ScheduleAction(m *schedule.ScheduleAction, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartWorkflow(); v != nil {
		if err := visitMemos_workflow_NewWorkflowExecutionInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_schedule_ScheduleListEntry(m *schedule.ScheduleListEntry, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflow_NewWorkflowExecutionInfo(m *workflow.NewWorkflowExecutionInfo, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflow_WorkflowExecutionInfo(m *workflow.WorkflowExecutionInfo, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_CreateScheduleRequest(m *workflowservice.CreateScheduleRequest, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	if v := m.GetSchedule(); v != nil {
		if err := visitMemos_schedule_Schedule(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_DescribeScheduleResponse(m *workflowservice.DescribeScheduleResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	if v := m.GetSchedule(); v != nil {
		if err := visitMemos_schedule_Schedule(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_DescribeWorkflowExecutionResponse(m *workflowservice.DescribeWorkflowExecutionResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetWorkflowExecutionInfo(); v != nil {
		if err := visitMemos_workflow_WorkflowExecutionInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_ExecuteMultiOperationRequest(m *workflowservice.ExecuteMultiOperationRequest, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetOperations() {
		if v != nil {
			if err := visitMemos_workflowservice_ExecuteMultiOperationRequest_Operation(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_ExecuteMultiOperationRequest_Operation(m *workflowservice.ExecuteMultiOperationRequest_Operation, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartWorkflow(); v != nil {
		if err := visitMemos_workflowservice_StartWorkflowExecutionRequest(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_ExecuteMultiOperationResponse(m *workflowservice.ExecuteMultiOperationResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetResponses() {
		if v != nil {
			if err := visitMemos_workflowservice_ExecuteMultiOperationResponse_Response(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_ExecuteMultiOperationResponse_Response(m *workflowservice.ExecuteMultiOperationResponse_Response, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartWorkflow(); v != nil {
		if err := visitMemos_workflowservice_StartWorkflowExecutionResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_GetWorkflowExecutionHistoryResponse(m *workflowservice.GetWorkflowExecutionHistoryResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHistory(); v != nil {
		if err := visitMemos_history_History(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_GetWorkflowExecutionHistoryReverseResponse(m *workflowservice.GetWorkflowExecutionHistoryReverseResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHistory(); v != nil {
		if err := visitMemos_history_History(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_ListArchivedWorkflowExecutionsResponse(m *workflowservice.ListArchivedWorkflowExecutionsResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitMemos_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_ListClosedWorkflowExecutionsResponse(m *workflowservice.ListClosedWorkflowExecutionsResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitMemos_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_ListOpenWorkflowExecutionsResponse(m *workflowservice.ListOpenWorkflowExecutionsResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitMemos_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_ListSchedulesResponse(m *workflowservice.ListSchedulesResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetSchedules() {
		if v != nil {
			if err := visitMemos_schedule_ScheduleListEntry(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_ListWorkflowExecutionsResponse(m *workflowservice.ListWorkflowExecutionsResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitMemos_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_PollWorkflowTaskQueueResponse(m *workflowservice.PollWorkflowTaskQueueResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHistory(); v != nil {
		if err := visitMemos_history_History(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_RespondWorkflowTaskCompletedRequest(m *workflowservice.RespondWorkflowTaskCompletedRequest, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetCommands() {
		if v != nil {
			if err := visitMemos_command_Command(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_RespondWorkflowTaskCompletedResponse(m *workflowservice.RespondWorkflowTaskCompletedResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetWorkflowTask(); v != nil {
		if err := visitMemos_workflowservice_PollWorkflowTaskQueueResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_ScanWorkflowExecutionsResponse(m *workflowservice.ScanWorkflowExecutionsResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitMemos_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitMemos_workflowservice_SignalWithStartWorkflowExecutionRequest(m *workflowservice.SignalWithStartWorkflowExecutionRequest, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_StartWorkflowExecutionRequest(m *workflowservice.StartWorkflowExecutionRequest, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_StartWorkflowExecutionResponse(m *workflowservice.StartWorkflowExecutionResponse, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetEagerWorkflowTask(); v != nil {
		if err := visitMemos_workflowservice_PollWorkflowTaskQueueResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitMemos_workflowservice_UpdateScheduleRequest(m *workflowservice.UpdateScheduleRequest, cb func(*common.Memo) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	if v := m.GetSchedule(); v != nil {
		if err := visitMemos_schedule_Schedule(v, cb); err != nil {
			return err
		}
	}
	return nil
}
