// Code generated by cmd/codegen. DO NOT EDIT.

package visit_test

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"

	"github.com/temporalio/temporal-proxy/internal/visit"
	"github.com/temporalio/temporal-proxy/internal/visit/visitcheck"
)

func TestMemos_CreateScheduleRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.CreateScheduleRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_DescribeScheduleResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeScheduleResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_DescribeWorkflowExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeWorkflowExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ExecuteMultiOperationRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ExecuteMultiOperationRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ExecuteMultiOperationResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ExecuteMultiOperationResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_GetWorkflowExecutionHistoryResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetWorkflowExecutionHistoryResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_GetWorkflowExecutionHistoryReverseResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetWorkflowExecutionHistoryReverseResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ListArchivedWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListArchivedWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ListClosedWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListClosedWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ListOpenWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListOpenWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ListSchedulesResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListSchedulesResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ListWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_PollWorkflowTaskQueueResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.PollWorkflowTaskQueueResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_RespondWorkflowTaskCompletedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondWorkflowTaskCompletedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_RespondWorkflowTaskCompletedResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondWorkflowTaskCompletedResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_ScanWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ScanWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_SignalWithStartWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.SignalWithStartWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_StartWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.StartWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_StartWorkflowExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.StartWorkflowExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestMemos_UpdateScheduleRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateScheduleRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Memo
			handled, err := visit.Memos(variant, func(p *common.Memo) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Memo{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}
