// Code generated by cmd/codegen. DO NOT EDIT.

package visit_test

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	common "go.temporal.io/api/common/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"

	"github.com/temporalio/temporal-proxy/internal/visit"
	"github.com/temporalio/temporal-proxy/internal/visit/visitcheck"
)

func TestPayloads_CountActivityExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.CountActivityExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_CountSchedulesResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.CountSchedulesResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_CountWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.CountWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_CreateScheduleRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.CreateScheduleRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_CreateWorkerDeploymentVersionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.CreateWorkerDeploymentVersionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_DescribeActivityExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeActivityExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_DescribeDeploymentResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeDeploymentResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_DescribeScheduleResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeScheduleResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_DescribeWorkerDeploymentVersionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeWorkerDeploymentVersionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_DescribeWorkflowExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.DescribeWorkflowExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ExecuteMultiOperationRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ExecuteMultiOperationRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ExecuteMultiOperationResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ExecuteMultiOperationResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_GetCurrentDeploymentResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetCurrentDeploymentResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_GetDeploymentReachabilityResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetDeploymentReachabilityResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_GetWorkflowExecutionHistoryResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetWorkflowExecutionHistoryResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_GetWorkflowExecutionHistoryReverseResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.GetWorkflowExecutionHistoryReverseResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ListActivityExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListActivityExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ListArchivedWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListArchivedWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ListClosedWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListClosedWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ListOpenWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListOpenWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ListSchedulesResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListSchedulesResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ListWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ListWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_PollActivityExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.PollActivityExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_PollActivityTaskQueueResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.PollActivityTaskQueueResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_PollNexusTaskQueueResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.PollNexusTaskQueueResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_PollWorkflowExecutionUpdateResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.PollWorkflowExecutionUpdateResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_PollWorkflowTaskQueueResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.PollWorkflowTaskQueueResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_QueryWorkflowRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.QueryWorkflowRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_QueryWorkflowResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.QueryWorkflowResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RecordActivityTaskHeartbeatByIdRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RecordActivityTaskHeartbeatByIdRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RecordActivityTaskHeartbeatRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RecordActivityTaskHeartbeatRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ResetWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ResetWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskCanceledByIdRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskCanceledByIdRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskCanceledRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskCanceledRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskCompletedByIdRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskCompletedByIdRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskCompletedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskCompletedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskFailedByIdRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskFailedByIdRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskFailedByIdResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskFailedByIdResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskFailedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskFailedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondActivityTaskFailedResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondActivityTaskFailedResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondNexusTaskCompletedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondNexusTaskCompletedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondNexusTaskFailedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondNexusTaskFailedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondQueryTaskCompletedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondQueryTaskCompletedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondWorkflowTaskCompletedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondWorkflowTaskCompletedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondWorkflowTaskCompletedResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondWorkflowTaskCompletedResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_RespondWorkflowTaskFailedRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.RespondWorkflowTaskFailedRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ScanWorkflowExecutionsResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ScanWorkflowExecutionsResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_SetCurrentDeploymentRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.SetCurrentDeploymentRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_SetCurrentDeploymentResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.SetCurrentDeploymentResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_SignalWithStartWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.SignalWithStartWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_SignalWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.SignalWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_StartActivityExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.StartActivityExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_StartBatchOperationRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.StartBatchOperationRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_StartWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.StartWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_StartWorkflowExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.StartWorkflowExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_TerminateWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.TerminateWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_UpdateScheduleRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateScheduleRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_UpdateWorkerDeploymentVersionComputeConfigRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateWorkerDeploymentVersionComputeConfigRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_UpdateWorkerDeploymentVersionMetadataRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateWorkerDeploymentVersionMetadataRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_UpdateWorkerDeploymentVersionMetadataResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateWorkerDeploymentVersionMetadataResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_UpdateWorkflowExecutionRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateWorkflowExecutionRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_UpdateWorkflowExecutionResponse(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.UpdateWorkflowExecutionResponse{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}

func TestPayloads_ValidateWorkerDeploymentVersionComputeConfigRequest(t *testing.T) {
	t.Parallel()

	for i, variant := range visitcheck.Variants(&workflowservice.ValidateWorkerDeploymentVersionComputeConfigRequest{}) {
		t.Run(fmt.Sprintf("variant_%d", i), func(t *testing.T) {
			t.Parallel()

			var got []*common.Payload
			handled, err := visit.Payloads(variant, func(p *common.Payload) error {
				got = append(got, p)
				return nil
			})
			require.NoError(t, err)
			require.True(t, handled)

			want := visitcheck.Collect(variant, (&common.Payload{}).ProtoReflect().Descriptor().FullName())
			require.ElementsMatch(t, visitcheck.Addrs(want), visitcheck.Addrs(got))
		})
	}
}
