// Code generated by cmd/codegen. DO NOT EDIT.

// Field visitors for visit. Map iteration order is not deterministic,
// so callbacks for fields stored in maps may run in any order.

package visit

import (
	activity "go.temporal.io/api/activity/v1"
	batch "go.temporal.io/api/batch/v1"
	command "go.temporal.io/api/command/v1"
	common "go.temporal.io/api/common/v1"
	compute "go.temporal.io/api/compute/v1"
	deployment "go.temporal.io/api/deployment/v1"
	failure "go.temporal.io/api/failure/v1"
	history "go.temporal.io/api/history/v1"
	nexus "go.temporal.io/api/nexus/v1"
	query "go.temporal.io/api/query/v1"
	schedule "go.temporal.io/api/schedule/v1"
	sdk "go.temporal.io/api/sdk/v1"
	update "go.temporal.io/api/update/v1"
	workflow "go.temporal.io/api/workflow/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	proto "google.golang.org/protobuf/proto"
)

// Payloads invokes cb for every common.Payload reachable in msg. It returns
// true if msg was a recognized request or response type.
func Payloads(msg proto.Message, cb func(*common.Payload) error) (bool, error) {
	switch m := msg.(type) {
	case *workflowservice.CountActivityExecutionsResponse:
		return true, visitPayloads_workflowservice_CountActivityExecutionsResponse(m, cb)
	case *workflowservice.CountSchedulesResponse:
		return true, visitPayloads_workflowservice_CountSchedulesResponse(m, cb)
	case *workflowservice.CountWorkflowExecutionsResponse:
		return true, visitPayloads_workflowservice_CountWorkflowExecutionsResponse(m, cb)
	case *workflowservice.CreateScheduleRequest:
		return true, visitPayloads_workflowservice_CreateScheduleRequest(m, cb)
	case *workflowservice.CreateWorkerDeploymentVersionRequest:
		return true, visitPayloads_workflowservice_CreateWorkerDeploymentVersionRequest(m, cb)
	case *workflowservice.DescribeActivityExecutionResponse:
		return true, visitPayloads_workflowservice_DescribeActivityExecutionResponse(m, cb)
	case *workflowservice.DescribeDeploymentResponse:
		return true, visitPayloads_workflowservice_DescribeDeploymentResponse(m, cb)
	case *workflowservice.DescribeScheduleResponse:
		return true, visitPayloads_workflowservice_DescribeScheduleResponse(m, cb)
	case *workflowservice.DescribeWorkerDeploymentVersionResponse:
		return true, visitPayloads_workflowservice_DescribeWorkerDeploymentVersionResponse(m, cb)
	case *workflowservice.DescribeWorkflowExecutionResponse:
		return true, visitPayloads_workflowservice_DescribeWorkflowExecutionResponse(m, cb)
	case *workflowservice.ExecuteMultiOperationRequest:
		return true, visitPayloads_workflowservice_ExecuteMultiOperationRequest(m, cb)
	case *workflowservice.ExecuteMultiOperationResponse:
		return true, visitPayloads_workflowservice_ExecuteMultiOperationResponse(m, cb)
	case *workflowservice.GetCurrentDeploymentResponse:
		return true, visitPayloads_workflowservice_GetCurrentDeploymentResponse(m, cb)
	case *workflowservice.GetDeploymentReachabilityResponse:
		return true, visitPayloads_workflowservice_GetDeploymentReachabilityResponse(m, cb)
	case *workflowservice.GetWorkflowExecutionHistoryResponse:
		return true, visitPayloads_workflowservice_GetWorkflowExecutionHistoryResponse(m, cb)
	case *workflowservice.GetWorkflowExecutionHistoryReverseResponse:
		return true, visitPayloads_workflowservice_GetWorkflowExecutionHistoryReverseResponse(m, cb)
	case *workflowservice.ListActivityExecutionsResponse:
		return true, visitPayloads_workflowservice_ListActivityExecutionsResponse(m, cb)
	case *workflowservice.ListArchivedWorkflowExecutionsResponse:
		return true, visitPayloads_workflowservice_ListArchivedWorkflowExecutionsResponse(m, cb)
	case *workflowservice.ListClosedWorkflowExecutionsResponse:
		return true, visitPayloads_workflowservice_ListClosedWorkflowExecutionsResponse(m, cb)
	case *workflowservice.ListOpenWorkflowExecutionsResponse:
		return true, visitPayloads_workflowservice_ListOpenWorkflowExecutionsResponse(m, cb)
	case *workflowservice.ListSchedulesResponse:
		return true, visitPayloads_workflowservice_ListSchedulesResponse(m, cb)
	case *workflowservice.ListWorkflowExecutionsResponse:
		return true, visitPayloads_workflowservice_ListWorkflowExecutionsResponse(m, cb)
	case *workflowservice.PollActivityExecutionResponse:
		return true, visitPayloads_workflowservice_PollActivityExecutionResponse(m, cb)
	case *workflowservice.PollActivityTaskQueueResponse:
		return true, visitPayloads_workflowservice_PollActivityTaskQueueResponse(m, cb)
	case *workflowservice.PollNexusTaskQueueResponse:
		return true, visitPayloads_workflowservice_PollNexusTaskQueueResponse(m, cb)
	case *workflowservice.PollWorkflowExecutionUpdateResponse:
		return true, visitPayloads_workflowservice_PollWorkflowExecutionUpdateResponse(m, cb)
	case *workflowservice.PollWorkflowTaskQueueResponse:
		return true, visitPayloads_workflowservice_PollWorkflowTaskQueueResponse(m, cb)
	case *workflowservice.QueryWorkflowRequest:
		return true, visitPayloads_workflowservice_QueryWorkflowRequest(m, cb)
	case *workflowservice.QueryWorkflowResponse:
		return true, visitPayloads_workflowservice_QueryWorkflowResponse(m, cb)
	case *workflowservice.RecordActivityTaskHeartbeatByIdRequest:
		return true, visitPayloads_workflowservice_RecordActivityTaskHeartbeatByIdRequest(m, cb)
	case *workflowservice.RecordActivityTaskHeartbeatRequest:
		return true, visitPayloads_workflowservice_RecordActivityTaskHeartbeatRequest(m, cb)
	case *workflowservice.ResetWorkflowExecutionRequest:
		return true, visitPayloads_workflowservice_ResetWorkflowExecutionRequest(m, cb)
	case *workflowservice.RespondActivityTaskCanceledByIdRequest:
		return true, visitPayloads_workflowservice_RespondActivityTaskCanceledByIdRequest(m, cb)
	case *workflowservice.RespondActivityTaskCanceledRequest:
		return true, visitPayloads_workflowservice_RespondActivityTaskCanceledRequest(m, cb)
	case *workflowservice.RespondActivityTaskCompletedByIdRequest:
		return true, visitPayloads_workflowservice_RespondActivityTaskCompletedByIdRequest(m, cb)
	case *workflowservice.RespondActivityTaskCompletedRequest:
		return true, visitPayloads_workflowservice_RespondActivityTaskCompletedRequest(m, cb)
	case *workflowservice.RespondActivityTaskFailedByIdRequest:
		return true, visitPayloads_workflowservice_RespondActivityTaskFailedByIdRequest(m, cb)
	case *workflowservice.RespondActivityTaskFailedByIdResponse:
		return true, visitPayloads_workflowservice_RespondActivityTaskFailedByIdResponse(m, cb)
	case *workflowservice.RespondActivityTaskFailedRequest:
		return true, visitPayloads_workflowservice_RespondActivityTaskFailedRequest(m, cb)
	case *workflowservice.RespondActivityTaskFailedResponse:
		return true, visitPayloads_workflowservice_RespondActivityTaskFailedResponse(m, cb)
	case *workflowservice.RespondNexusTaskCompletedRequest:
		return true, visitPayloads_workflowservice_RespondNexusTaskCompletedRequest(m, cb)
	case *workflowservice.RespondNexusTaskFailedRequest:
		return true, visitPayloads_workflowservice_RespondNexusTaskFailedRequest(m, cb)
	case *workflowservice.RespondQueryTaskCompletedRequest:
		return true, visitPayloads_workflowservice_RespondQueryTaskCompletedRequest(m, cb)
	case *workflowservice.RespondWorkflowTaskCompletedRequest:
		return true, visitPayloads_workflowservice_RespondWorkflowTaskCompletedRequest(m, cb)
	case *workflowservice.RespondWorkflowTaskCompletedResponse:
		return true, visitPayloads_workflowservice_RespondWorkflowTaskCompletedResponse(m, cb)
	case *workflowservice.RespondWorkflowTaskFailedRequest:
		return true, visitPayloads_workflowservice_RespondWorkflowTaskFailedRequest(m, cb)
	case *workflowservice.ScanWorkflowExecutionsResponse:
		return true, visitPayloads_workflowservice_ScanWorkflowExecutionsResponse(m, cb)
	case *workflowservice.SetCurrentDeploymentRequest:
		return true, visitPayloads_workflowservice_SetCurrentDeploymentRequest(m, cb)
	case *workflowservice.SetCurrentDeploymentResponse:
		return true, visitPayloads_workflowservice_SetCurrentDeploymentResponse(m, cb)
	case *workflowservice.SignalWithStartWorkflowExecutionRequest:
		return true, visitPayloads_workflowservice_SignalWithStartWorkflowExecutionRequest(m, cb)
	case *workflowservice.SignalWorkflowExecutionRequest:
		return true, visitPayloads_workflowservice_SignalWorkflowExecutionRequest(m, cb)
	case *workflowservice.StartActivityExecutionRequest:
		return true, visitPayloads_workflowservice_StartActivityExecutionRequest(m, cb)
	case *workflowservice.StartBatchOperationRequest:
		return true, visitPayloads_workflowservice_StartBatchOperationRequest(m, cb)
	case *workflowservice.StartWorkflowExecutionRequest:
		return true, visitPayloads_workflowservice_StartWorkflowExecutionRequest(m, cb)
	case *workflowservice.StartWorkflowExecutionResponse:
		return true, visitPayloads_workflowservice_StartWorkflowExecutionResponse(m, cb)
	case *workflowservice.TerminateWorkflowExecutionRequest:
		return true, visitPayloads_workflowservice_TerminateWorkflowExecutionRequest(m, cb)
	case *workflowservice.UpdateScheduleRequest:
		return true, visitPayloads_workflowservice_UpdateScheduleRequest(m, cb)
	case *workflowservice.UpdateWorkerDeploymentVersionComputeConfigRequest:
		return true, visitPayloads_workflowservice_UpdateWorkerDeploymentVersionComputeConfigRequest(m, cb)
	case *workflowservice.UpdateWorkerDeploymentVersionMetadataRequest:
		return true, visitPayloads_workflowservice_UpdateWorkerDeploymentVersionMetadataRequest(m, cb)
	case *workflowservice.UpdateWorkerDeploymentVersionMetadataResponse:
		return true, visitPayloads_workflowservice_UpdateWorkerDeploymentVersionMetadataResponse(m, cb)
	case *workflowservice.UpdateWorkflowExecutionRequest:
		return true, visitPayloads_workflowservice_UpdateWorkflowExecutionRequest(m, cb)
	case *workflowservice.UpdateWorkflowExecutionResponse:
		return true, visitPayloads_workflowservice_UpdateWorkflowExecutionResponse(m, cb)
	case *workflowservice.ValidateWorkerDeploymentVersionComputeConfigRequest:
		return true, visitPayloads_workflowservice_ValidateWorkerDeploymentVersionComputeConfigRequest(m, cb)
	default:
		return false, nil
	}
}

func visitPayloads_activity_ActivityExecutionInfo(m *activity.ActivityExecutionInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_activity_ActivityExecutionListInfo(m *activity.ActivityExecutionListInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_activity_ActivityExecutionOutcome(m *activity.ActivityExecutionOutcome, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_batch_BatchOperationReset(m *batch.BatchOperationReset, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetPostResetOperations() {
		if v != nil {
			if err := visitPayloads_workflow_PostResetOperation(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_batch_BatchOperationSignal(m *batch.BatchOperationSignal, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_batch_BatchOperationTermination(m *batch.BatchOperationTermination, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_CancelWorkflowExecutionCommandAttributes(m *command.CancelWorkflowExecutionCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_Command(m *command.Command, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetCancelWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitPayloads_command_CancelWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetCompleteWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitPayloads_command_CompleteWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetContinueAsNewWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitPayloads_command_ContinueAsNewWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetFailWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitPayloads_command_FailWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetModifyWorkflowPropertiesCommandAttributes(); v != nil {
		if err := visitPayloads_command_ModifyWorkflowPropertiesCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetRecordMarkerCommandAttributes(); v != nil {
		if err := visitPayloads_command_RecordMarkerCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetScheduleActivityTaskCommandAttributes(); v != nil {
		if err := visitPayloads_command_ScheduleActivityTaskCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetScheduleNexusOperationCommandAttributes(); v != nil {
		if err := visitPayloads_command_ScheduleNexusOperationCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSignalExternalWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitPayloads_command_SignalExternalWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetStartChildWorkflowExecutionCommandAttributes(); v != nil {
		if err := visitPayloads_command_StartChildWorkflowExecutionCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUpsertWorkflowSearchAttributesCommandAttributes(); v != nil {
		if err := visitPayloads_command_UpsertWorkflowSearchAttributesCommandAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_CompleteWorkflowExecutionCommandAttributes(m *command.CompleteWorkflowExecutionCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_ContinueAsNewWorkflowExecutionCommandAttributes(m *command.ContinueAsNewWorkflowExecutionCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastCompletionResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_FailWorkflowExecutionCommandAttributes(m *command.FailWorkflowExecutionCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_ModifyWorkflowPropertiesCommandAttributes(m *command.ModifyWorkflowPropertiesCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpsertedMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_RecordMarkerCommandAttributes(m *command.RecordMarkerCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetDetails() {
		if v != nil {
			if err := visitPayloads_common_Payloads(v, cb); err != nil {
				return err
			}
		}
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_ScheduleActivityTaskCommandAttributes(m *command.ScheduleActivityTaskCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_ScheduleNexusOperationCommandAttributes(m *command.ScheduleNexusOperationCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetInput(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_SignalExternalWorkflowExecutionCommandAttributes(m *command.SignalExternalWorkflowExecutionCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_StartChildWorkflowExecutionCommandAttributes(m *command.StartChildWorkflowExecutionCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_command_UpsertWorkflowSearchAttributesCommandAttributes(m *command.UpsertWorkflowSearchAttributesCommandAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_common_Header(m *common.Header, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetFields() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_common_Memo(m *common.Memo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetFields() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_common_Payloads(m *common.Payloads, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetPayloads() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_common_SearchAttributes(m *common.SearchAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetIndexedFields() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_compute_ComputeConfig(m *compute.ComputeConfig, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetScalingGroups() {
		if v != nil {
			if err := visitPayloads_compute_ComputeConfigScalingGroup(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_compute_ComputeConfigScalingGroup(m *compute.ComputeConfigScalingGroup, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetProvider(); v != nil {
		if err := visitPayloads_compute_ComputeProvider(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetScaler(); v != nil {
		if err := visitPayloads_compute_ComputeScaler(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_compute_ComputeConfigScalingGroupUpdate(m *compute.ComputeConfigScalingGroupUpdate, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetScalingGroup(); v != nil {
		if err := visitPayloads_compute_ComputeConfigScalingGroup(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_compute_ComputeProvider(m *compute.ComputeProvider, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_compute_ComputeScaler(m *compute.ComputeScaler, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_deployment_DeploymentInfo(m *deployment.DeploymentInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetMetadata() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_deployment_UpdateDeploymentMetadata(m *deployment.UpdateDeploymentMetadata, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetUpsertEntries() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_deployment_VersionMetadata(m *deployment.VersionMetadata, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetEntries() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_deployment_WorkerDeploymentVersionInfo(m *deployment.WorkerDeploymentVersionInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetComputeConfig(); v != nil {
		if err := visitPayloads_compute_ComputeConfig(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMetadata(); v != nil {
		if err := visitPayloads_deployment_VersionMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_failure_ApplicationFailureInfo(m *failure.ApplicationFailureInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_failure_CanceledFailureInfo(m *failure.CanceledFailureInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_failure_Failure(m *failure.Failure, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetApplicationFailureInfo(); v != nil {
		if err := visitPayloads_failure_ApplicationFailureInfo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetCanceledFailureInfo(); v != nil {
		if err := visitPayloads_failure_CanceledFailureInfo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetCause(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetEncodedAttributes(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	if v := m.GetResetWorkflowFailureInfo(); v != nil {
		if err := visitPayloads_failure_ResetWorkflowFailureInfo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetTimeoutFailureInfo(); v != nil {
		if err := visitPayloads_failure_TimeoutFailureInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_failure_ResetWorkflowFailureInfo(m *failure.ResetWorkflowFailureInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetLastHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_failure_TimeoutFailureInfo(m *failure.TimeoutFailureInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetLastHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ActivityTaskCanceledEventAttributes(m *history.ActivityTaskCanceledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ActivityTaskCompletedEventAttributes(m *history.ActivityTaskCompletedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ActivityTaskFailedEventAttributes(m *history.ActivityTaskFailedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ActivityTaskScheduledEventAttributes(m *history.ActivityTaskScheduledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ActivityTaskStartedEventAttributes(m *history.ActivityTaskStartedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetLastFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ActivityTaskTimedOutEventAttributes(m *history.ActivityTaskTimedOutEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ChildWorkflowExecutionCanceledEventAttributes(m *history.ChildWorkflowExecutionCanceledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ChildWorkflowExecutionCompletedEventAttributes(m *history.ChildWorkflowExecutionCompletedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ChildWorkflowExecutionFailedEventAttributes(m *history.ChildWorkflowExecutionFailedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_ChildWorkflowExecutionStartedEventAttributes(m *history.ChildWorkflowExecutionStartedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_History(m *history.History, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetEvents() {
		if v != nil {
			if err := visitPayloads_history_HistoryEvent(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_history_HistoryEvent(m *history.HistoryEvent, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetActivityTaskCanceledEventAttributes(); v != nil {
		if err := visitPayloads_history_ActivityTaskCanceledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetActivityTaskCompletedEventAttributes(); v != nil {
		if err := visitPayloads_history_ActivityTaskCompletedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetActivityTaskFailedEventAttributes(); v != nil {
		if err := visitPayloads_history_ActivityTaskFailedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetActivityTaskScheduledEventAttributes(); v != nil {
		if err := visitPayloads_history_ActivityTaskScheduledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetActivityTaskStartedEventAttributes(); v != nil {
		if err := visitPayloads_history_ActivityTaskStartedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetActivityTaskTimedOutEventAttributes(); v != nil {
		if err := visitPayloads_history_ActivityTaskTimedOutEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetChildWorkflowExecutionCanceledEventAttributes(); v != nil {
		if err := visitPayloads_history_ChildWorkflowExecutionCanceledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetChildWorkflowExecutionCompletedEventAttributes(); v != nil {
		if err := visitPayloads_history_ChildWorkflowExecutionCompletedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetChildWorkflowExecutionFailedEventAttributes(); v != nil {
		if err := visitPayloads_history_ChildWorkflowExecutionFailedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetChildWorkflowExecutionStartedEventAttributes(); v != nil {
		if err := visitPayloads_history_ChildWorkflowExecutionStartedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMarkerRecordedEventAttributes(); v != nil {
		if err := visitPayloads_history_MarkerRecordedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetNexusOperationCancelRequestFailedEventAttributes(); v != nil {
		if err := visitPayloads_history_NexusOperationCancelRequestFailedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetNexusOperationCanceledEventAttributes(); v != nil {
		if err := visitPayloads_history_NexusOperationCanceledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetNexusOperationCompletedEventAttributes(); v != nil {
		if err := visitPayloads_history_NexusOperationCompletedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetNexusOperationFailedEventAttributes(); v != nil {
		if err := visitPayloads_history_NexusOperationFailedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetNexusOperationScheduledEventAttributes(); v != nil {
		if err := visitPayloads_history_NexusOperationScheduledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetNexusOperationTimedOutEventAttributes(); v != nil {
		if err := visitPayloads_history_NexusOperationTimedOutEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSignalExternalWorkflowExecutionInitiatedEventAttributes(); v != nil {
		if err := visitPayloads_history_SignalExternalWorkflowExecutionInitiatedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetStartChildWorkflowExecutionInitiatedEventAttributes(); v != nil {
		if err := visitPayloads_history_StartChildWorkflowExecutionInitiatedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUpsertWorkflowSearchAttributesEventAttributes(); v != nil {
		if err := visitPayloads_history_UpsertWorkflowSearchAttributesEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionCanceledEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionCanceledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionCompletedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionCompletedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionContinuedAsNewEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionContinuedAsNewEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionFailedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionFailedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionSignaledEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionSignaledEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionStartedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionStartedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionTerminatedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionTerminatedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionUpdateAcceptedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionUpdateAcceptedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionUpdateAdmittedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionUpdateAdmittedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionUpdateCompletedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionUpdateCompletedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowExecutionUpdateRejectedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowExecutionUpdateRejectedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowPropertiesModifiedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowPropertiesModifiedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowPropertiesModifiedExternallyEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowPropertiesModifiedExternallyEventAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetWorkflowTaskFailedEventAttributes(); v != nil {
		if err := visitPayloads_history_WorkflowTaskFailedEventAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_MarkerRecordedEventAttributes(m *history.MarkerRecordedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetDetails() {
		if v != nil {
			if err := visitPayloads_common_Payloads(v, cb); err != nil {
				return err
			}
		}
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_NexusOperationCancelRequestFailedEventAttributes(m *history.NexusOperationCancelRequestFailedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_NexusOperationCanceledEventAttributes(m *history.NexusOperationCanceledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_NexusOperationCompletedEventAttributes(m *history.NexusOperationCompletedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_NexusOperationFailedEventAttributes(m *history.NexusOperationFailedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_NexusOperationScheduledEventAttributes(m *history.NexusOperationScheduledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetInput(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_NexusOperationTimedOutEventAttributes(m *history.NexusOperationTimedOutEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_SignalExternalWorkflowExecutionInitiatedEventAttributes(m *history.SignalExternalWorkflowExecutionInitiatedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_StartChildWorkflowExecutionInitiatedEventAttributes(m *history.StartChildWorkflowExecutionInitiatedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_UpsertWorkflowSearchAttributesEventAttributes(m *history.UpsertWorkflowSearchAttributesEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionCanceledEventAttributes(m *history.WorkflowExecutionCanceledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionCompletedEventAttributes(m *history.WorkflowExecutionCompletedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionContinuedAsNewEventAttributes(m *history.WorkflowExecutionContinuedAsNewEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastCompletionResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionFailedEventAttributes(m *history.WorkflowExecutionFailedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionSignaledEventAttributes(m *history.WorkflowExecutionSignaledEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionStartedEventAttributes(m *history.WorkflowExecutionStartedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetContinuedFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastCompletionResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionTerminatedEventAttributes(m *history.WorkflowExecutionTerminatedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionUpdateAcceptedEventAttributes(m *history.WorkflowExecutionUpdateAcceptedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetAcceptedRequest(); v != nil {
		if err := visitPayloads_update_Request(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionUpdateAdmittedEventAttributes(m *history.WorkflowExecutionUpdateAdmittedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetRequest(); v != nil {
		if err := visitPayloads_update_Request(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionUpdateCompletedEventAttributes(m *history.WorkflowExecutionUpdateCompletedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetOutcome(); v != nil {
		if err := visitPayloads_update_Outcome(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowExecutionUpdateRejectedEventAttributes(m *history.WorkflowExecutionUpdateRejectedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetRejectedRequest(); v != nil {
		if err := visitPayloads_update_Request(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowPropertiesModifiedEventAttributes(m *history.WorkflowPropertiesModifiedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpsertedMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowPropertiesModifiedExternallyEventAttributes(m *history.WorkflowPropertiesModifiedExternallyEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpsertedMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_history_WorkflowTaskFailedEventAttributes(m *history.WorkflowTaskFailedEventAttributes, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_nexus_Request(m *nexus.Request, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartOperation(); v != nil {
		if err := visitPayloads_nexus_StartOperationRequest(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_nexus_Response(m *nexus.Response, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartOperation(); v != nil {
		if err := visitPayloads_nexus_StartOperationResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_nexus_StartOperationRequest(m *nexus.StartOperationRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetPayload(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_nexus_StartOperationResponse(m *nexus.StartOperationResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSyncSuccess(); v != nil {
		if err := visitPayloads_nexus_StartOperationResponse_Sync(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_nexus_StartOperationResponse_Sync(m *nexus.StartOperationResponse_Sync, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetPayload(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_query_WorkflowQuery(m *query.WorkflowQuery, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetQueryArgs(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_query_WorkflowQueryResult(m *query.WorkflowQueryResult, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetAnswer(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_schedule_Schedule(m *schedule.Schedule, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetAction(); v != nil {
		if err := visitPayloads_schedule_ScheduleAction(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_schedule_ScheduleAction(m *schedule.ScheduleAction, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartWorkflow(); v != nil {
		if err := visitPayloads_workflow_NewWorkflowExecutionInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_schedule_ScheduleListEntry(m *schedule.ScheduleListEntry, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_sdk_UserMetadata(m *sdk.UserMetadata, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	if v := m.GetSummary(); v != nil {
		if err := cb(v); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_update_Input(m *update.Input, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetArgs(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_update_Outcome(m *update.Outcome, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSuccess(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_update_Request(m *update.Request, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_update_Input(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_CallbackInfo(m *workflow.CallbackInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetLastAttemptFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_NewWorkflowExecutionInfo(m *workflow.NewWorkflowExecutionInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_NexusOperationCancellationInfo(m *workflow.NexusOperationCancellationInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetLastAttemptFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_PendingActivityInfo(m *workflow.PendingActivityInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_PendingNexusOperationInfo(m *workflow.PendingNexusOperationInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetCancellationInfo(); v != nil {
		if err := visitPayloads_workflow_NexusOperationCancellationInfo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastAttemptFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_PostResetOperation(m *workflow.PostResetOperation, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetSignalWorkflow(); v != nil {
		if err := visitPayloads_workflow_PostResetOperation_SignalWorkflow(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_PostResetOperation_SignalWorkflow(m *workflow.PostResetOperation_SignalWorkflow, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_WorkflowExecutionConfig(m *workflow.WorkflowExecutionConfig, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflow_WorkflowExecutionInfo(m *workflow.WorkflowExecutionInfo, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_CountActivityExecutionsResponse(m *workflowservice.CountActivityExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetGroups() {
		if v != nil {
			if err := visitPayloads_workflowservice_CountActivityExecutionsResponse_AggregationGroup(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_CountActivityExecutionsResponse_AggregationGroup(m *workflowservice.CountActivityExecutionsResponse_AggregationGroup, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetGroupValues() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_CountSchedulesResponse(m *workflowservice.CountSchedulesResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetGroups() {
		if v != nil {
			if err := visitPayloads_workflowservice_CountSchedulesResponse_AggregationGroup(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_CountSchedulesResponse_AggregationGroup(m *workflowservice.CountSchedulesResponse_AggregationGroup, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetGroupValues() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_CountWorkflowExecutionsResponse(m *workflowservice.CountWorkflowExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetGroups() {
		if v != nil {
			if err := visitPayloads_workflowservice_CountWorkflowExecutionsResponse_AggregationGroup(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_CountWorkflowExecutionsResponse_AggregationGroup(m *workflowservice.CountWorkflowExecutionsResponse_AggregationGroup, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetGroupValues() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_CreateScheduleRequest(m *workflowservice.CreateScheduleRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSchedule(); v != nil {
		if err := visitPayloads_schedule_Schedule(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_CreateWorkerDeploymentVersionRequest(m *workflowservice.CreateWorkerDeploymentVersionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetComputeConfig(); v != nil {
		if err := visitPayloads_compute_ComputeConfig(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_DescribeActivityExecutionResponse(m *workflowservice.DescribeActivityExecutionResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetInfo(); v != nil {
		if err := visitPayloads_activity_ActivityExecutionInfo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetOutcome(); v != nil {
		if err := visitPayloads_activity_ActivityExecutionOutcome(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_DescribeDeploymentResponse(m *workflowservice.DescribeDeploymentResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDeploymentInfo(); v != nil {
		if err := visitPayloads_deployment_DeploymentInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_DescribeScheduleResponse(m *workflowservice.DescribeScheduleResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSchedule(); v != nil {
		if err := visitPayloads_schedule_Schedule(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_DescribeWorkerDeploymentVersionResponse(m *workflowservice.DescribeWorkerDeploymentVersionResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetWorkerDeploymentVersionInfo(); v != nil {
		if err := visitPayloads_deployment_WorkerDeploymentVersionInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_DescribeWorkflowExecutionResponse(m *workflowservice.DescribeWorkflowExecutionResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetCallbacks() {
		if v != nil {
			if err := visitPayloads_workflow_CallbackInfo(v, cb); err != nil {
				return err
			}
		}
	}
	if v := m.GetExecutionConfig(); v != nil {
		if err := visitPayloads_workflow_WorkflowExecutionConfig(v, cb); err != nil {
			return err
		}
	}
	for _, v := range m.GetPendingActivities() {
		if v != nil {
			if err := visitPayloads_workflow_PendingActivityInfo(v, cb); err != nil {
				return err
			}
		}
	}
	for _, v := range m.GetPendingNexusOperations() {
		if v != nil {
			if err := visitPayloads_workflow_PendingNexusOperationInfo(v, cb); err != nil {
				return err
			}
		}
	}
	if v := m.GetWorkflowExecutionInfo(); v != nil {
		if err := visitPayloads_workflow_WorkflowExecutionInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_ExecuteMultiOperationRequest(m *workflowservice.ExecuteMultiOperationRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetOperations() {
		if v != nil {
			if err := visitPayloads_workflowservice_ExecuteMultiOperationRequest_Operation(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ExecuteMultiOperationRequest_Operation(m *workflowservice.ExecuteMultiOperationRequest_Operation, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartWorkflow(); v != nil {
		if err := visitPayloads_workflowservice_StartWorkflowExecutionRequest(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUpdateWorkflow(); v != nil {
		if err := visitPayloads_workflowservice_UpdateWorkflowExecutionRequest(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_ExecuteMultiOperationResponse(m *workflowservice.ExecuteMultiOperationResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetResponses() {
		if v != nil {
			if err := visitPayloads_workflowservice_ExecuteMultiOperationResponse_Response(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ExecuteMultiOperationResponse_Response(m *workflowservice.ExecuteMultiOperationResponse_Response, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetStartWorkflow(); v != nil {
		if err := visitPayloads_workflowservice_StartWorkflowExecutionResponse(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUpdateWorkflow(); v != nil {
		if err := visitPayloads_workflowservice_UpdateWorkflowExecutionResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_GetCurrentDeploymentResponse(m *workflowservice.GetCurrentDeploymentResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetCurrentDeploymentInfo(); v != nil {
		if err := visitPayloads_deployment_DeploymentInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_GetDeploymentReachabilityResponse(m *workflowservice.GetDeploymentReachabilityResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDeploymentInfo(); v != nil {
		if err := visitPayloads_deployment_DeploymentInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_GetWorkflowExecutionHistoryResponse(m *workflowservice.GetWorkflowExecutionHistoryResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHistory(); v != nil {
		if err := visitPayloads_history_History(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_GetWorkflowExecutionHistoryReverseResponse(m *workflowservice.GetWorkflowExecutionHistoryReverseResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHistory(); v != nil {
		if err := visitPayloads_history_History(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_ListActivityExecutionsResponse(m *workflowservice.ListActivityExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitPayloads_activity_ActivityExecutionListInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ListArchivedWorkflowExecutionsResponse(m *workflowservice.ListArchivedWorkflowExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitPayloads_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ListClosedWorkflowExecutionsResponse(m *workflowservice.ListClosedWorkflowExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitPayloads_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ListOpenWorkflowExecutionsResponse(m *workflowservice.ListOpenWorkflowExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitPayloads_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ListSchedulesResponse(m *workflowservice.ListSchedulesResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetSchedules() {
		if v != nil {
			if err := visitPayloads_schedule_ScheduleListEntry(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_ListWorkflowExecutionsResponse(m *workflowservice.ListWorkflowExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitPayloads_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_PollActivityExecutionResponse(m *workflowservice.PollActivityExecutionResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetOutcome(); v != nil {
		if err := visitPayloads_activity_ActivityExecutionOutcome(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_PollActivityTaskQueueResponse(m *workflowservice.PollActivityTaskQueueResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_PollNexusTaskQueueResponse(m *workflowservice.PollNexusTaskQueueResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetRequest(); v != nil {
		if err := visitPayloads_nexus_Request(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_PollWorkflowExecutionUpdateResponse(m *workflowservice.PollWorkflowExecutionUpdateResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetOutcome(); v != nil {
		if err := visitPayloads_update_Outcome(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_PollWorkflowTaskQueueResponse(m *workflowservice.PollWorkflowTaskQueueResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHistory(); v != nil {
		if err := visitPayloads_history_History(v, cb); err != nil {
			return err
		}
	}
	for _, v := range m.GetQueries() {
		if v != nil {
			if err := visitPayloads_query_WorkflowQuery(v, cb); err != nil {
				return err
			}
		}
	}
	if v := m.GetQuery(); v != nil {
		if err := visitPayloads_query_WorkflowQuery(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_QueryWorkflowRequest(m *workflowservice.QueryWorkflowRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetQuery(); v != nil {
		if err := visitPayloads_query_WorkflowQuery(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_QueryWorkflowResponse(m *workflowservice.QueryWorkflowResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetQueryResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RecordActivityTaskHeartbeatByIdRequest(m *workflowservice.RecordActivityTaskHeartbeatByIdRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RecordActivityTaskHeartbeatRequest(m *workflowservice.RecordActivityTaskHeartbeatRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_ResetWorkflowExecutionRequest(m *workflowservice.ResetWorkflowExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetPostResetOperations() {
		if v != nil {
			if err := visitPayloads_workflow_PostResetOperation(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskCanceledByIdRequest(m *workflowservice.RespondActivityTaskCanceledByIdRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskCanceledRequest(m *workflowservice.RespondActivityTaskCanceledRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskCompletedByIdRequest(m *workflowservice.RespondActivityTaskCompletedByIdRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskCompletedRequest(m *workflowservice.RespondActivityTaskCompletedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskFailedByIdRequest(m *workflowservice.RespondActivityTaskFailedByIdRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskFailedByIdResponse(m *workflowservice.RespondActivityTaskFailedByIdResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetFailures() {
		if v != nil {
			if err := visitPayloads_failure_Failure(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskFailedRequest(m *workflowservice.RespondActivityTaskFailedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastHeartbeatDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondActivityTaskFailedResponse(m *workflowservice.RespondActivityTaskFailedResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetFailures() {
		if v != nil {
			if err := visitPayloads_failure_Failure(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondNexusTaskCompletedRequest(m *workflowservice.RespondNexusTaskCompletedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResponse(); v != nil {
		if err := visitPayloads_nexus_Response(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondNexusTaskFailedRequest(m *workflowservice.RespondNexusTaskFailedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondQueryTaskCompletedRequest(m *workflowservice.RespondQueryTaskCompletedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetQueryResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondWorkflowTaskCompletedRequest(m *workflowservice.RespondWorkflowTaskCompletedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetCommands() {
		if v != nil {
			if err := visitPayloads_command_Command(v, cb); err != nil {
				return err
			}
		}
	}
	for _, v := range m.GetQueryResults() {
		if v != nil {
			if err := visitPayloads_query_WorkflowQueryResult(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondWorkflowTaskCompletedResponse(m *workflowservice.RespondWorkflowTaskCompletedResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetActivityTasks() {
		if v != nil {
			if err := visitPayloads_workflowservice_PollActivityTaskQueueResponse(v, cb); err != nil {
				return err
			}
		}
	}
	if v := m.GetWorkflowTask(); v != nil {
		if err := visitPayloads_workflowservice_PollWorkflowTaskQueueResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_RespondWorkflowTaskFailedRequest(m *workflowservice.RespondWorkflowTaskFailedRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_ScanWorkflowExecutionsResponse(m *workflowservice.ScanWorkflowExecutionsResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetExecutions() {
		if v != nil {
			if err := visitPayloads_workflow_WorkflowExecutionInfo(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_SetCurrentDeploymentRequest(m *workflowservice.SetCurrentDeploymentRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetUpdateMetadata(); v != nil {
		if err := visitPayloads_deployment_UpdateDeploymentMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_SetCurrentDeploymentResponse(m *workflowservice.SetCurrentDeploymentResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetCurrentDeploymentInfo(); v != nil {
		if err := visitPayloads_deployment_DeploymentInfo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetPreviousDeploymentInfo(); v != nil {
		if err := visitPayloads_deployment_DeploymentInfo(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_SignalWithStartWorkflowExecutionRequest(m *workflowservice.SignalWithStartWorkflowExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSignalInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_SignalWorkflowExecutionRequest(m *workflowservice.SignalWorkflowExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_StartActivityExecutionRequest(m *workflowservice.StartActivityExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_StartBatchOperationRequest(m *workflowservice.StartBatchOperationRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetResetOperation(); v != nil {
		if err := visitPayloads_batch_BatchOperationReset(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSignalOperation(); v != nil {
		if err := visitPayloads_batch_BatchOperationSignal(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetTerminationOperation(); v != nil {
		if err := visitPayloads_batch_BatchOperationTermination(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_StartWorkflowExecutionRequest(m *workflowservice.StartWorkflowExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetContinuedFailure(); v != nil {
		if err := visitPayloads_failure_Failure(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetHeader(); v != nil {
		if err := visitPayloads_common_Header(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetInput(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetLastCompletionResult(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetUserMetadata(); v != nil {
		if err := visitPayloads_sdk_UserMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_StartWorkflowExecutionResponse(m *workflowservice.StartWorkflowExecutionResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetEagerWorkflowTask(); v != nil {
		if err := visitPayloads_workflowservice_PollWorkflowTaskQueueResponse(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_TerminateWorkflowExecutionRequest(m *workflowservice.TerminateWorkflowExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetDetails(); v != nil {
		if err := visitPayloads_common_Payloads(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_UpdateScheduleRequest(m *workflowservice.UpdateScheduleRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMemo(); v != nil {
		if err := visitPayloads_common_Memo(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSchedule(); v != nil {
		if err := visitPayloads_schedule_Schedule(v, cb); err != nil {
			return err
		}
	}
	if v := m.GetSearchAttributes(); v != nil {
		if err := visitPayloads_common_SearchAttributes(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_UpdateWorkerDeploymentVersionComputeConfigRequest(m *workflowservice.UpdateWorkerDeploymentVersionComputeConfigRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetComputeConfigScalingGroups() {
		if v != nil {
			if err := visitPayloads_compute_ComputeConfigScalingGroupUpdate(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_UpdateWorkerDeploymentVersionMetadataRequest(m *workflowservice.UpdateWorkerDeploymentVersionMetadataRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetUpsertEntries() {
		if v != nil {
			if err := cb(v); err != nil {
				return err
			}
		}
	}
	return nil
}

func visitPayloads_workflowservice_UpdateWorkerDeploymentVersionMetadataResponse(m *workflowservice.UpdateWorkerDeploymentVersionMetadataResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetMetadata(); v != nil {
		if err := visitPayloads_deployment_VersionMetadata(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_UpdateWorkflowExecutionRequest(m *workflowservice.UpdateWorkflowExecutionRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetRequest(); v != nil {
		if err := visitPayloads_update_Request(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_UpdateWorkflowExecutionResponse(m *workflowservice.UpdateWorkflowExecutionResponse, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	if v := m.GetOutcome(); v != nil {
		if err := visitPayloads_update_Outcome(v, cb); err != nil {
			return err
		}
	}
	return nil
}

func visitPayloads_workflowservice_ValidateWorkerDeploymentVersionComputeConfigRequest(m *workflowservice.ValidateWorkerDeploymentVersionComputeConfigRequest, cb func(*common.Payload) error) error {
	if m == nil {
		return nil
	}
	for _, v := range m.GetComputeConfigScalingGroups() {
		if v != nil {
			if err := visitPayloads_compute_ComputeConfigScalingGroupUpdate(v, cb); err != nil {
				return err
			}
		}
	}
	return nil
}
