// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/temporalio/temporal-proxy/internal/transport (interfaces: ConnectionFactory,ConnectionManager,SessionFactory,SessionListener)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package transport_test -typed . ConnectionFactory,ConnectionManager,SessionFactory,SessionListener
//

// Package transport_test is a generated GoMock package.
package transport_test

import (
	net "net"
	reflect "reflect"

	yamux "github.com/hashicorp/yamux"
	transport "github.com/temporalio/temporal-proxy/internal/transport"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionFactory is a mock of ConnectionFactory interface.
type MockConnectionFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionFactoryMockRecorder
	isgomock struct{}
}

// MockConnectionFactoryMockRecorder is the mock recorder for MockConnectionFactory.
type MockConnectionFactoryMockRecorder struct {
	mock *MockConnectionFactory
}

// NewMockConnectionFactory creates a new mock instance.
func NewMockConnectionFactory(ctrl *gomock.Controller) *MockConnectionFactory {
	mock := &MockConnectionFactory{ctrl: ctrl}
	mock.recorder = &MockConnectionFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionFactory) EXPECT() *MockConnectionFactoryMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockConnectionFactory) Address() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(string)
	return ret0
}

// Address indicates an expected call of Address.
func (mr *MockConnectionFactoryMockRecorder) Address() *MockConnectionFactoryAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockConnectionFactory)(nil).Address))
	return &MockConnectionFactoryAddressCall{Call: call}
}

// MockConnectionFactoryAddressCall wrap *gomock.Call
type MockConnectionFactoryAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionFactoryAddressCall) Return(arg0 string) *MockConnectionFactoryAddressCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionFactoryAddressCall) Do(f func() string) *MockConnectionFactoryAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionFactoryAddressCall) DoAndReturn(f func() string) *MockConnectionFactoryAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Done mocks base method.
func (m *MockConnectionFactory) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockConnectionFactoryMockRecorder) Done() *MockConnectionFactoryDoneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockConnectionFactory)(nil).Done))
	return &MockConnectionFactoryDoneCall{Call: call}
}

// MockConnectionFactoryDoneCall wrap *gomock.Call
type MockConnectionFactoryDoneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionFactoryDoneCall) Return(arg0 <-chan struct{}) *MockConnectionFactoryDoneCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionFactoryDoneCall) Do(f func() <-chan struct{}) *MockConnectionFactoryDoneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionFactoryDoneCall) DoAndReturn(f func() <-chan struct{}) *MockConnectionFactoryDoneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewConnection mocks base method.
func (m *MockConnectionFactory) NewConnection() (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConnection")
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConnection indicates an expected call of NewConnection.
func (mr *MockConnectionFactoryMockRecorder) NewConnection() *MockConnectionFactoryNewConnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnection", reflect.TypeOf((*MockConnectionFactory)(nil).NewConnection))
	return &MockConnectionFactoryNewConnectionCall{Call: call}
}

// MockConnectionFactoryNewConnectionCall wrap *gomock.Call
type MockConnectionFactoryNewConnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionFactoryNewConnectionCall) Return(arg0 net.Conn, arg1 error) *MockConnectionFactoryNewConnectionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionFactoryNewConnectionCall) Do(f func() (net.Conn, error)) *MockConnectionFactoryNewConnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionFactoryNewConnectionCall) DoAndReturn(f func() (net.Conn, error)) *MockConnectionFactoryNewConnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockConnectionManager is a mock of ConnectionManager interface.
type MockConnectionManager struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionManagerMockRecorder
	isgomock struct{}
}

// MockConnectionManagerMockRecorder is the mock recorder for MockConnectionManager.
type MockConnectionManagerMockRecorder struct {
	mock *MockConnectionManager
}

// NewMockConnectionManager creates a new mock instance.
func NewMockConnectionManager(ctrl *gomock.Controller) *MockConnectionManager {
	mock := &MockConnectionManager{ctrl: ctrl}
	mock.recorder = &MockConnectionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionManager) EXPECT() *MockConnectionManagerMockRecorder {
	return m.recorder
}

// AddConnection mocks base method.
func (m *MockConnectionManager) AddConnection(arg0 net.Conn, arg1 *yamux.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddConnection", arg0, arg1)
}

// AddConnection indicates an expected call of AddConnection.
func (mr *MockConnectionManagerMockRecorder) AddConnection(arg0, arg1 any) *MockConnectionManagerAddConnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConnection", reflect.TypeOf((*MockConnectionManager)(nil).AddConnection), arg0, arg1)
	return &MockConnectionManagerAddConnectionCall{Call: call}
}

// MockConnectionManagerAddConnectionCall wrap *gomock.Call
type MockConnectionManagerAddConnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionManagerAddConnectionCall) Return() *MockConnectionManagerAddConnectionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionManagerAddConnectionCall) Do(f func(net.Conn, *yamux.Session)) *MockConnectionManagerAddConnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionManagerAddConnectionCall) DoAndReturn(f func(net.Conn, *yamux.Session)) *MockConnectionManagerAddConnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionFactory is a mock of SessionFactory interface.
type MockSessionFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSessionFactoryMockRecorder
	isgomock struct{}
}

// MockSessionFactoryMockRecorder is the mock recorder for MockSessionFactory.
type MockSessionFactoryMockRecorder struct {
	mock *MockSessionFactory
}

// NewMockSessionFactory creates a new mock instance.
func NewMockSessionFactory(ctrl *gomock.Controller) *MockSessionFactory {
	mock := &MockSessionFactory{ctrl: ctrl}
	mock.recorder = &MockSessionFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionFactory) EXPECT() *MockSessionFactoryMockRecorder {
	return m.recorder
}

// NewSession mocks base method.
func (m *MockSessionFactory) NewSession(arg0 net.Conn) (*yamux.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession", arg0)
	ret0, _ := ret[0].(*yamux.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSession indicates an expected call of NewSession.
func (mr *MockSessionFactoryMockRecorder) NewSession(arg0 any) *MockSessionFactoryNewSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockSessionFactory)(nil).NewSession), arg0)
	return &MockSessionFactoryNewSessionCall{Call: call}
}

// MockSessionFactoryNewSessionCall wrap *gomock.Call
type MockSessionFactoryNewSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionFactoryNewSessionCall) Return(arg0 *yamux.Session, arg1 error) *MockSessionFactoryNewSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionFactoryNewSessionCall) Do(f func(net.Conn) (*yamux.Session, error)) *MockSessionFactoryNewSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionFactoryNewSessionCall) DoAndReturn(f func(net.Conn) (*yamux.Session, error)) *MockSessionFactoryNewSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionListener is a mock of SessionListener interface.
type MockSessionListener struct {
	ctrl     *gomock.Controller
	recorder *MockSessionListenerMockRecorder
	isgomock struct{}
}

// MockSessionListenerMockRecorder is the mock recorder for MockSessionListener.
type MockSessionListenerMockRecorder struct {
	mock *MockSessionListener
}

// NewMockSessionListener creates a new mock instance.
func NewMockSessionListener(ctrl *gomock.Controller) *MockSessionListener {
	mock := &MockSessionListener{ctrl: ctrl}
	mock.recorder = &MockSessionListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionListener) EXPECT() *MockSessionListenerMockRecorder {
	return m.recorder
}

// OnSessionsUpdated mocks base method.
func (m *MockSessionListener) OnSessionsUpdated(arg0 map[string]*transport.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSessionsUpdated", arg0)
}

// OnSessionsUpdated indicates an expected call of OnSessionsUpdated.
func (mr *MockSessionListenerMockRecorder) OnSessionsUpdated(arg0 any) *MockSessionListenerOnSessionsUpdatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSessionsUpdated", reflect.TypeOf((*MockSessionListener)(nil).OnSessionsUpdated), arg0)
	return &MockSessionListenerOnSessionsUpdatedCall{Call: call}
}

// MockSessionListenerOnSessionsUpdatedCall wrap *gomock.Call
type MockSessionListenerOnSessionsUpdatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionListenerOnSessionsUpdatedCall) Return() *MockSessionListenerOnSessionsUpdatedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionListenerOnSessionsUpdatedCall) Do(f func(map[string]*transport.Session)) *MockSessionListenerOnSessionsUpdatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionListenerOnSessionsUpdatedCall) DoAndReturn(f func(map[string]*transport.Session)) *MockSessionListenerOnSessionsUpdatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
